### ISSUE TITLE
Update virus statuses for files

### ISSUE THREAD

**Issue by awead** [psu-libraries/scholarsphere#1009]
With the 4.6.2 release, metadata-listener will now check for viruses when files are uploaded. We will need to go back and update the statuses for files that were migrated and files that were uploaded post-migration.

### Bulk update migrated files

It's reasonable to assume all the files that were uploaded to Scholarsphere 3 don't have any viruses. If they did, we would have found them when they were first uploaded, or during a scan of the file system.

Grab a list of work versions that were migrated and update their files:
``` ruby
PaperTrail::Version.select(:item_id).where(whodunnit: "gid://scholarsphere/ExternalApp/1", item_type: "WorkVersion", event: "create").map do |work_version|
  work_version.files.map do |file|
    file.file_attacher.add_metadata("virus" => { "status" => "false", "scanned_at" => work_version.created_at })
    file.file_attacher.write
    file.save
  end
end
```

### Update any remaining files that have a nil virus status

Probably something like:

``` ruby
FileResource.find_each.map do |file|
  status = file.file_data.dig('metadata', 'virus', 'status')
  
  raise StandardError, "whoops!" if status == 'true'

  MetadataListener::Job.perform_later(args) if status.nil?
end
```

**Comment by whereismyjetpack** [comment]
I couldn't get the records via papertrail, for some reason. Some of the records didn't have paper trail records, and not all objects on the `FileResource` were available to me. I ran the following on qa, and a preview deployment to verify 

```
FileResource.where("file_data->'metadata'->'virus'->'status'='null'").each do |f|
  f.file_data['metadata']['virus']['status'] = false
  f.file_data['metadata']['virus']['scanned_at'] = f.created_at
 f.save
end
```
```
irb(main):023:0> f = FileResource.where("file_data->'metadata'->'virus'->'status'='null'")
irb(main):024:0> f.length
=> 0
```

If there are no objections, I can update the records in prod later today

**Comment by awead** [comment]
That could be because the when the work versions are deleted, the file resource records remain. So you're seeing files resource that have to related paper trail records because their associated work versions were deleted. In any case, what you have above should be fine.

**Comment by whereismyjetpack** [comment]
This work was done in prod
