### ISSUE TITLE
Work's withdrawn version should not 404

### ISSUE THREAD

**Issue by awead** [psu-libraries/scholarsphere#1022]
# Bug Report

## Description

If the work url points to a withdrawn version, it should not 404.

## To Reproduce
1. publish a new work
2. withdrawn the only version
3. visit the work resource url

## Expected behavior

Display the work's metadata. It should be as if it's a restricted resource. We should not be able to see or download files, and see the withdrawn message.

**Comment by awead** [comment]
@srerickson With the upcoming changes in #1010 and the problems in #765, I think this needs to change so that both draft work versions _ and works_ render and not return 404. This would make them just like withdrawn, embargoed, or Penn State works: their metadata is displayed with no access to files.

We could explore some refinements and maybe splat the work "draft" over the background, and/or possible limit the metadata display even further, but I think it has to resolve.

**Comment by srerickson** [comment]
@awead that works for me.

**Comment by awead** [comment]
Related to #970. Draft works also need to resolve.
