### ISSUE TITLE
Valid EDTF Publication Date Causes Server Error

### ISSUE THREAD

**Issue by srerickson** [psu-libraries/scholarsphere#1038]
# Bug Report

## Description

The publication date field must be EDTF but some EDTF dates cause a server error when saving/rendering. For example, the date "2010/2020" is valid but causes error:

```ruby
    error: ActionView::Template::Error: undefined method `year' for #<EDTF::Interval:0x00007fa7651a6800> 
```

## To Reproduce
1. Create a new work
2. Set the publication date to an interval "2010/2020"
3. Try to publish the work

## Expected behavior
Valid EDTF dates shouldn't cause a server error.

**Comment by awead** [comment]
@srerickson The error is coming from our Google Scholar metatags, which specifically require a year. If it's a valid EDTF date, it'll figure something out. However, "2010/2020" is an `EDTF::Interval` so we have to decide what to do. Options are:

1. Return the year of the earliest range, i.e. 2010
2. Return the year of the latest ranage, i.e. 2020
3. Return the year of the deposit date
4. Return nothing

Currently, if the date isn't EDTF, it returns the deposited year. I'd probably opt for this (option 3) and anything that isn't a valid `EDTF::Date` just gets the published year.
