### ISSUE TITLE
Admins can't delete collections

### ISSUE THREAD

**Issue by srerickson** [psu-libraries/scholarsphere#1045]
# Bug Report

Admins can't delete collection

## Description
When an admin tries to delete a collection they didn't create, it doesn't work.

## To Reproduce
1. Enable admin privs on QA server
2. On QA, find a collection you didn't create
3. Try to delete it.

**Comment by awead** [comment]
We're authorizing only from the current user's list of available collections. Instead, we need to authorize _any_ collection. We're already doing this in `edit` and `update` actions, so change `destroy` to look like:

``` ruby
def destroy
  @collection = Collection.find(params[:id])
  authorize(@collection)
  ...
```

The tests might not need to change, but could be at least re-worded. Bonus points for adding a `when logged in as admin` context.
