### ISSUE TITLE
Inconsistency in file download links

### ISSUE THREAD

**Issue by srerickson** [psu-libraries/scholarsphere#1048]
# Bug Report

## Description
On the work page, there is inconsistency between the `citation_pdf_url`(s) in `head` and the download link(s) in `body`. Shouldn't these be the same?

## To Reproduce
1. Go to the page for a work
2. view source and compare the links in the head to the links in the body

## Expected behavior
Shouldn't they be the same?

**Comment by awead** [comment]
It looks like the meta tag is calling `file_resources` whereas the resource page is calling the `file_version_memberships` which are the junction objects between a work version and a file resource. Technically, they both point to the same file, although the file version membership might hold a different name for the file. They should probably both use `file_version_memberships` to avoid confusion.
