### ISSUE TITLE
Message for withdrawn versions that newer version exists

### ISSUE THREAD

**Issue by srerickson** [psu-libraries/scholarsphere#1059]
# Feature Request

When viewing a __withdrawn__ work version for a work with a more recent published version, a message should appear at the top of the work:

> This version has been withdrawn. [View the current version](*link to work*).

**Comment by srerickson** [comment]
can this be closed?

**Comment by ajkiessl** [comment]
@srerickson I think this might be completed already considering what Adam posted here: https://github.com/psu-libraries/scholarsphere/pull/1061 .

However, I'm having trouble recreating a "Withdrawn work version" scenario to confirm.  The only option I can find as an admin is to delete the most recent version.

**Comment by ajkiessl** [comment]
Okay, I just messed with some things in the backend locally to reproduce.  Just like what Adam shows in #1061, this is how a withdrawn version with a newer published version looks:

![Screen Shot 2022-01-27 at 2 52 50 PM](https://user-images.githubusercontent.com/32677188/151433950-66361c7e-59a1-4e35-bfb0-26dac13537c4.png)

I think this is probably sufficient.

**Comment by srerickson** [comment]
Sorry @ajkiessl I missed my own note to check if this can be closed -- I think it can.
