### ISSUE TITLE
Combine edit and create buttons in the resource page

### ISSUE THREAD

**Issue by awead** [psu-libraries/scholarsphere#1078]
Depending on the state of the resource, you can either edit or create. We don't need separate buttons for this.

## WDLL

* a single button that states either "Edit" or "Create" depending on what's available to the user
* admins will have a separate button to edit versions that have already been published

**Comment by srerickson** [comment]
I would like to have "tooltips" for the update and work settings buttons:

- Update: "Change resource description or content."
- Work Settings: "Manage access settings, embargoes, DOIs, and more."

**Comment by srerickson** [comment]
@nicktiberi - Can you add an icon appropriate to an "edit" action (e.g., pencil) to the update button to correspond with the gear icon in the work settings button?
