### ISSUE TITLE
Move version list to the right-hand page

### ISSUE THREAD

**Issue by awead** [psu-libraries/scholarsphere#1080]
List versions after metadata and remove the dropdown from the blue bar. This is borrowed from Zenodo.

## Examples

![Screen Shot 2021-06-14 at 9 43 06 AM](https://user-images.githubusercontent.com/312085/121902189-179ab200-ccf5-11eb-817c-967c822bcc9b.png)
![Screen Shot 2021-06-14 at 9 42 32 AM](https://user-images.githubusercontent.com/312085/121902192-179ab200-ccf5-11eb-8736-06c42b362d5c.png)

## WDLL

* update the component that renders the drop down
* create a new section between metadata and analytics
* create a fixed-height or scrollable section

**Comment by srerickson** [comment]
@nicktiberi I think the preview branch looks good. Just two things I'd like to try:
- Remove the time from the dates
- Add a place for small help text at the bottom of the box. It can just be filler text for now.

**Comment by nicktiberi** [comment]
@srerickson - see below. Let me know if you'd like me to push these changes to the preview branch.

<img width="576" alt="Screen Shot 2021-06-22 at 9 30 49 AM" src="https://user-images.githubusercontent.com/639920/122933388-9c607e00-d33c-11eb-9743-d330f8b70b99.png">

**Comment by srerickson** [comment]
@nicktiberi  - This is perfect. Thanks!

**Comment by srerickson** [comment]
@nicktiberi lets merge without the text at the bottom (we may add this later)
