### ISSUE TITLE
Make collection edit button consistent with work edit button

### ISSUE THREAD

**Issue by awead** [psu-libraries/scholarsphere#1082]
Corresponds to changes in #1078. Ensure that buttons for collection edit look the same as work edit.

## WDLL

* move collection edit button to the left of collection settings
* use the same view component ?

**Comment by nicktiberi** [comment]
@srerickson - since we are now adding a new "Update Work" button, should the "Edit" button for collections now say "Update Collection" to be consistent?

**Comment by srerickson** [comment]
@nicktiberi - yes, that would be great. Thanks for the suggestion.
