### ISSUE TITLE
"No Copyright" License Option

### ISSUE THREAD

**Issue by srerickson** [psu-libraries/scholarsphere#1103]
# Feature Request

Ana has recommended replacing the "public domain" option with "no copyright" (https://rightsstatements.org/page/NoC-US/1.0/)

- Set currently active public domain option to inactive
- Add new active option for "No Copyright": https://rightsstatements.org/page/NoC-US/1.0/

**Comment by anaelizabethenriquez** [comment]
The text for this, if it happens, should be "No Copyright - United States" or "No Copyright - U.S.," not just "No Copyright."

**Comment by nicktiberi** [comment]
@srerickson - it looks like this has been implemented. Can this issue be closed?
