### ISSUE TITLE
Make Resource Settings Button a Component

### ISSUE THREAD

**Issue by nicktiberi** [psu-libraries/scholarsphere#1105]
# Feature Request
We've already moved the Edit Resource button into a component, so let's do the same for Resource Settings.

## What does "done" look like?
The Resource Settings button is moved into a reusable component, and that component is used on the Work Version and Collection details pages.

**Comment by awead** [comment]
The two buttons look almost identical, except for text and icons. We _could_ have a `ResourceButton` super class with the html template, so you're files would look something like:

```
app/components/resource_button.rb
app/components/resource_button.html.erb
app/components/edit_resource_button.rb
app/components/edit_settings_button.rb
```

``` ruby
class EditResourceButton < ResourceButton; end
class EditSettingsButton < ResourceButton; end
```

Not that the two subclasses don't have any template files. The component gem will look for templates in the super classes if it doesn't fine any. That way the template can be shared across the different buttons, so they are rendered similarly, but the logic for the labels, icons, css, etc. is in the Ruby class.
