### ISSUE TITLE
Thumbnails for works and collections

### ISSUE THREAD

**Issue by awead** [psu-libraries/scholarsphere#1114]
# Feature Request

- [x] Works and Collections can have thumbnails with same size and placement as current placeholder graphics.
- [x] UI on work settings page to upload a thumbnail image, with recommended dimensions.
- [x] Uploaded thumbnails are automatically scaled/cropped to necessary sizes (of current placeholder graphics).
- [x] Thumbnail appears on search results (list of resources view)
- [x] Thumbnail appears on resource display page (show resource view). See note below.

Nice, but not required:
- [x]  Thumbnail upload UI has an option to auto-generate a thumbnail from the content. (i.e., fist page of PDF).

# Placement of thumbnail on work/collection display page:

Thumbnails are not part of the existing resource display pages, so we will need to do some basic design work. For a first pass, let's include a "thumbnail" section in the metadata block on the right-side, below the title. We may want to explore other options.

**Comment by ajkiessl** [comment]
@srerickson I added this checkbox to the settings page for Works and Collections.  It allows users to toggle the thumbnail display 'on' or 'off'.  If it is toggled 'off', then one of the icons that we've been displaying will show in its place.

![Screen Shot 2022-02-08 at 3 50 18 PM](https://user-images.githubusercontent.com/32677188/153074263-9b1eee91-392b-4156-915f-53a86eaabe46.png)

It is defaulted to 'off'.  I figured we could roll this out at the end of this sprint with it defaulted to 'off', and if it seems like thumbnails are generating properly, then maybe default to 'on' later.

I'm going to get to work on the feature giving users the ability to upload their own thumbnail next, but that'll be in a separate branch/PR and probably won't be released until the end of the next sprint.

**Comment by srerickson** [comment]
@ajkiessl, this looks great. What are your thoughts on automatically generating thumbnails for all new submissions and changing the checkbox to "Use auto-generated thumbnail ..." (default to unchecked). Could we do that this sprint? The thing is, people will want to see the thumbnail before using it.
