### ISSUE TITLE
Re-envision the Resource Page

### ISSUE THREAD

**Issue by awead** [psu-libraries/scholarsphere#1115]
# Feature Request

## Describe the solution you'd like

Have a designed look at our resource page (with an implemented thumbnail) and redesign and/or tweak the layout and appearance of the entire page.

## What does "done" look like?

How will we know when we've successfully implemented this?

**Comment by srerickson** [comment]
closing this since it's not well specified. Current resource page with thumbnails is acceptable. We may need another round of design work in the near future, but we can create new issues if/when that time comes.
