### ISSUE TITLE
Don't Push the "Done" Button

### ISSUE THREAD

**Issue by awead** [psu-libraries/scholarsphere#1127]
# Bug Report

## Description

Pushing the "done" button on the files upload page. It makes the UI go away so it looks as if you haven't uploaded anything.

![Screen Shot 2021-09-03 at 10 30 04 AM](https://user-images.githubusercontent.com/312085/132022711-2a11156b-1fbb-4773-b84a-09573c3742b4.png)

## To Reproduce

1. Upload a file
2. Push "done"
3. Weep.

## Expected behavior

The list of files you've uploaded probably shouldn't go away? Or maybe the button doesn't need to be there.

**Comment by srerickson** [comment]
replace uploader?
