### ISSUE TITLE
Overwhelming the API

### ISSUE THREAD

**Issue by awead** [psu-libraries/scholarsphere#1132]
# Bug Report

## Description

When submitting many ingest requests to the API, the application can get backed up. Presently, this manifests itself with a Solr error: `Blacklight::Exceptions::ECONNREFUSED - Connection refused`.

Ideally this wouldn't happen because Solr should operate async and not block database updates or creates. However, these _is_ a theoretical limit as to how fast Scholarsphere can accept incoming ingest requests.

## To Reproduce

We're not 100% yet, but basically hammer the ingest api with requests, ~130 or more.

## Expected behavior

So long as we're within the acceptable limits of the application, the requests should go through. If that limit is exceeded, we should try rate limiting. See: https://github.com/rack/rack-attack/#ratelimit-headers-for-well-behaved-clients

## TODO

1. #1133 
2. Ensure Solr cannot block database procedures and that async jobs or other interactions don't "leak out" through the API 
3. Determine reasonable rate limit for ingests based on database and external service interactions
4. Use rate limit headers on the API

**Comment by whereismyjetpack** [comment]
we haven't seen issues in quite some time, I'm going to close this one.
