### ISSUE TITLE
Ability to opt out of monthly email reports

### ISSUE THREAD

**Issue by srerickson** [psu-libraries/scholarsphere#1142]
# Feature Request

Users should be able to opt out of receiving monthly emails about article downloads

## Describe the solution you'd like

On the profile page, there should be a checkbox for controlling this. Something like this:

__Email Settings__:
- [ ] Receive monthly report on downloads and views

**Comment by awead** [comment]
The field already exists in the database, and we're checking a user's preference when sending the emails, so I think all we need here is the UI checkbox.

**Comment by awead** [comment]
A "nice to have" would be a magic link in the email that would opt the user out right then and there. That's a little more complicated, but doable. This could be especially helpful if there was an issue where the user was no longer at Penn State and couldn't authenticate via Azure.

**Comment by banukutlu** [comment]
@srerickson  Is it OK if we reverse the language of the checkbox so it is aligned with the db column ie. `Opt out of monthly reports on downloads and views`?

**Comment by srerickson** [comment]
checking a box to *not* receive something seems strange to me. I'd prefer to invert the value instead of the language.
