### ISSUE TITLE
Basic search fails often: "Sorry, I don't understand your search."

### ISSUE THREAD

**Issue by srerickson** [psu-libraries/scholarsphere#1151]
# Bug Report

## Description
When searching all fields, the response is often "Sorry, I don't understand your search." I'm not sure what's going on but the search interface should be much more tolerant to varied user input. It shouldn't break for basic searches (see example).

## To Reproduce
1. from the homepage search: "Miniature magnetic rod interfacial stress rheometer for general-purpose microscopes"
2. see: "Sorry, I don't understand your search."

## Expected behavior
basic search should almost never "break" this way.

**Comment by whereismyjetpack** [comment]
related error message 
```
2021-12-07 16:54:33.086 ERROR (qtp286649365-618) [c:scholarsphere s:shard1 r:core_node30 x:scholarsphere_shard1_replica_n29] o.a.s.h.RequestHandlerBase org.apache.solr.common.SolrException: org.apache.solr.search.SyntaxError: Expected identifier at pos 74 str='{!dismax v=Miniature magnetic rod interfacial stress rheometer for general-purpose microscopes}'
```




```
>>> string = '{!dismax v=Miniature magnetic rod interfacial stress rheometer for general-purpose microscopes}'
>>> string[74]
'-'
```

looks like we might need to sanitize the input a bit, or something like this ?

**Comment by whereismyjetpack** [comment]
examples in splunk 
```
index=libraries org.apache.solr.search.SyntaxError 
| rex field=_raw "v=(?<query>.*)}\'"
| search query!=*org.eclipse*
| dedup query
| table query
```

**Comment by awead** [comment]
If you remove the hyphen, or put the entire search in quotes, it'll work. What's puzzling is that this is a Blacklight issue, and I thought that it would handle this.

**Comment by nicktiberi** [comment]
FYI, the following search  also produces "Sorry, I don't understand your search.":

`A Modern Soprano’s Guide to Puccini Arias`

Seems to be the apostrophe causing the issue, but it does not fail if the only word in the search is `Soprano's`.

**Comment by whereismyjetpack** [comment]
We are addressing this issue in the following deployment (https://scholarsphere-1151.dsrd.libraries.psu.edu/) The code for this deployment lives here (https://github.com/psu-libraries/scholarsphere/tree/preview/1151-dismax-q-escape)

**Comment by srerickson** [comment]
@banukutlu This looks great! Also seems to resolve some of the problems noted in #1186
