### ISSUE TITLE
Documentation/Help should be multi-page with auto-generated Nav & TOC

### ISSUE THREAD

**Issue by srerickson** [psu-libraries/scholarsphere#1152]
Currently the help page ("documentation and support") is just one static page, which doesn't allow for a lot of flexibility or expansion. ScholarSphere's documentation should be multiple pages with auto-generated navigation & table of contents.

Currently, we are using MKdocs to prepare a number of content and topic-specific guides ([repo](https://github.com/repub/scholarsphere-docs), [static site](https://repub.github.io/scholarsphere-docs/)). MKdocs works really well, but I would prefer to integrate this material into ScholarSphere more seamlessly, not leave it on a separate site. *What's the best way to do this?*

Update (1/25):

- We agreed on setting up a subdomain (`docs.scholarsphere.psu.edu`) with content served from a [GH pages site](https://github.com/repub/scholarsphere-docs).

To complete this issue, we should:

- [x] Make sure all content from current help pages is moved to new site. 
- [x] Create CNAME config for new site
- [x] Make documentation site content production ready.
- [x] Create a new setting `documentation_site`, or a way to handle the link to the documentation site in a rails-y way. 
- [x] the "Help" button should be a link to the documentation sites.
- [x] Update any static links to "https://scholarsphere.psu.edu/help" in markdown pages to "docs.scholarsphere.psu.edu"

**Comment by srerickson** [comment]
one solution is to generate static documentation pages as part of deployment. Another is to have pages generated on the first request and cached for future requests.

**Comment by srerickson** [comment]
@whereismyjetpack , I believe we agreed on `docs.scholarsphere.psu.edu` for the documentation site. Is there anything you need from me?

I'm updating the main issue (above) with additional tasks I think are necessary for completing this.

**Comment by whereismyjetpack** [comment]
I've put a request into central IT for a CNAME
