### ISSUE TITLE
notify users when they are given edit access to a work

### ISSUE THREAD

**Issue by srerickson** [psu-libraries/scholarsphere#1158]
# Feature Request

The UI for granting users edit access to a work or collection (on the Settings page) should include a checkbox that, if checked, causes an email to be sent to any users who have gained edit access to the work/collection as a result of the form submission. 

The label for the checkbox should read: "send notification email"

The email should read:

> SUBJECT: Edit Access for {abbreviated work title}
> 
> Dear {name},
> 
> You have been given edit access to the following {work/collection} on ScholarSphere: 
>    - {abbreviated work title}: {link}
> 
> If you believe you have been given edit access in error, please contact {scholarsphere contact email}
>

**Comment by srerickson** [comment]
Questions:
- How does this work for groups with edit access?
- How would this work if ORCID users are able to be given edit access?

**Comment by banukutlu** [comment]
@srerickson  what is the scholarsphere contact email?

**Comment by srerickson** [comment]
@banukutlu, contact is `scholarsphere@psu.edu`. This may be a config setting. If it's not maybe it should be? @whereismyjetpack ?

**Comment by srerickson** [comment]
@banukutlu, responding to questions from standup:

> How does this work for groups with edit access?

Let's just ignore groups for now for the purposes of this email. So, if a group is added to the permissions, no actions is taken to notify members of that group even if the box is checked.

>How would this work if ORCID users are able to be given edit access?

We'll handle that case in a different issue, when we know more about what we're doing with the ORCID integration.

> Should we notify users who are *removed* from the list of editors?

No. That would be rude.

> Should the checkbox on the user's profile page ("opt-out of monthly email reports") affect whether or not the email is sent?

No.
