### ISSUE TITLE
Prevent submissions that are "Penn State Only" with an open access license.

### ISSUE THREAD

**Issue by srerickson** [psu-libraries/scholarsphere#1184]
# Feature Request
Depositors sometimes select "Penn State Only" access and apply a license that would allow the Libraries to share the work publicly (i.e., any license other than "rights reserved"). In these case, the access setting and the license conflict with one another and we should do a better job to notify users about this conflict so they can change either the license or the access setting.

## Describe the solution you'd like

If a user selects "Penn State Only" access and an OA license (anything other than "In Copyright (Rights Reserved)") they get a warning:

> The access and license settings conflict with each other. Please set access to "Public" (preferred), or set the license to "In Copyright (Rights Reserved)." 

This validation should not prevent updates by administrators to existing works where the access and license settings are in conflict. 

We use URLs to identify licenses in `config/authorities/licenses.yml`. We might use a setting like the following to configure the validation above:

```yml
psu_access_required_license: [https://rightsstatements.org/page/InC/1.0/]
```

**Comment by rschenk** [comment]
> This validation should not prevent updates by administrators to existing works where the access and license settings are in conflict.

@srerickson remind me, do admins use the same form as plebeians to do this work? Or is there a special admin interface?

**Comment by srerickson** [comment]
admins use the same form, which probably complicates implementation of this.

**Comment by rschenk** [comment]
It sorta does complicate it, but also sorta doesn't because of the way Rails does validations. I have a plan.

**Comment by srerickson** [comment]
@rschenk might be worth keeping the big picture plan in mind as you do this (#1153) -- or not.
