### ISSUE TITLE
automation for merging works in a collection

### ISSUE THREAD

**Issue by srerickson** [psu-libraries/scholarsphere#1185]
# Feature Request

An unfortunate consequence of ScholarSphere's previous implementation of Collections is that there are many collections consisting of single-file works with filenames for titles. Here are some examples:

- [Soil Properties and Class 100m Grids United States](https://scholarsphere.psu.edu/resources/ea4b6c45-9eba-4b89-aba6-ff7246880fb1)
- [Callahan-Flintoft, C., & Wyble, B. (2017)](https://scholarsphere.psu.edu/resources/6bc12ca3-4d56-4e96-9558-dcfdb49e0cbe)
- [Leeman et al. 2014 JGR Data](https://scholarsphere.psu.edu/resources/8531040d-c55c-4f7e-a7c3-6bb57f623c08)

These collections shouldn't be collections, and their works shouldn't be works (They make my eyes bleed). Ultimately, I want to merge the works in these collections into a single work where possible. Doing this by hand would be too labor-intensive and error-prone, so I'd like to automate it as much as possible. What I have in mind is a rake task or the like to trigger a "merge collection" automation (case-by-case).

## Describe the solution you'd like

The automation would take a collection as its primary input; it would determine if the works in the collection can safely be merged, and it would perform the merge, delete the existing works, and add the new work to the collection. Details below:

To be safely merged, works in a collection MUST:
- all have a single file with a filename that maps in a predictable way to the title of the work [(for example)](https://scholarsphere.psu.edu/resources/62f10ddb-4b88-410e-9198-ae721c6f0044).
- all have unique titles in the context of the collection.
- all have the same access settings, license, work type, and publication date.

To be safely merged, works in a collection SHOULD:
- All have the same description
- All have the same creators and keywords (order may differ because of a bug in SS3)
- All have only one version

(The "SHOULD" checks can be overridden with a "force" parameter)

Works are merged by creating a new work with the following properties:
- Same title and description as the collection
- Same work type, access settings, license, publication date, etc. as shared by all the existing works.
- Files from each of the existing works, named for the existing work title (not the filename of the file in the existing work).

Once the work is created, remove the existing works and add the new work to the collection. The result should be a collection with a single work.

We will want to test this extensively in QA before using it in production.

**Comment by nicktiberi** [comment]
@srerickson - I finally got around to testing this in QA. The initial version of this merge functionality did not support the `force` param if certain things mismatch (description, etc). I was unsure if we would need it for the example collections in this issue, but after testing, it turns out that we do. Merges are failing due to mismatched work descriptions, etc.

Reopening this and will need to tweak the merge code to be more flexible.

**Comment by srerickson** [comment]
I'm not surprised that small differences in metadata are preventing merging in many cases. Ideally the tool could provide some feedback about the fields with conflicts. Then a curator can decide whether those conflicts are significant or if they can be safely ignored in a subsequent merge attempt.

It's also not a problem if the resulting merged work is left in draft state. In fact, it may make sense for this to be the default behavior. If some fields are ignored then there may be missing data in the new work and curator can fill these in by hand. The metadata is really easily fixable -- it's the files that are otherwise really tedious to bring together without this tool.

I think this workflow will ultimately require a fair amount of planning on the part of curators. It will help to have data from reports (#380) to identify collections that should be merged (and the fields that should be ignored when the merge is done).

**Comment by nicktiberi** [comment]
Per discussion with Seth:
- allow passing flags to ignore specific mismatched attributes (e.g. `--ignore-description`, etc)
- leave merged work unpublished so that a curator can edit it further before publishing
- consider a secondary service to overwrite the newly merged work's UUID with the UUID of the original collection

**Comment by srerickson** [comment]
As discussed with @nicktiberi,  we should break this into to tasks. The first generates a new draft work from items in the collection. Curators can then make changes to this work and publish it. A separate task replaces the collection with the new work: it removes the collection and assigns relevant identifiers associated with the collection to the work.

**Comment by srerickson** [comment]
@nicktiberi, would it make sense to move the parts of this automation that handle download/view statistics to the ` MigrateCollectionIds` service (#1242)?

Update: let me explain this more. If we're changing this automation so it just creates a draft work with the merged files from the collection then it probably doesn't make sense to transfer the view statistics. I think it makes more sense to handle the statistics in the `migration_collection_ids` service. Does that sound right?

**Comment by nicktiberi** [comment]
> @nicktiberi, would it make sense to move the parts of this automation that handle download/view statistics to the ` MigrateCollectionIds` service (#1242)?
> 
> Update: let me explain this more. If we're changing this automation is it just creates a draft works with the merged files from the collection then it doesn't make sense for it probably doesn't make sense to transfer the view statistics at this point. I think it makes more sense to handle the statistics in the `migration_collection_ids` service. Does that sound right?

Yeah, I think that totally makes sense. Otherwise we would not be migrating any views/downloads that were captured after the collection was merged into the new draft work.
