### ISSUE TITLE
Investigate field weightings for all field search

### ISSUE THREAD

**Issue by srerickson** [psu-libraries/scholarsphere#1186]
ScholarSphere's search results are a little baffling to me sometimes and I'd like to have a better sense of why.  Here is an example, searching for "A Modern Sopranos Guide to Puccini Arias":

- Google Scholar gives one result (from ScholarSphere): https://scholar.google.com/scholar?hl=en&as_sdt=0%2C27&q=A+Modern+Sopranos+Guide+to+Puccini+Arias&btnG=

- ScholarSphere gives a bunch of results, none of which are the right one: https://scholarsphere.psu.edu/catalog?q=A+Modern+Sopranos+Guide+to+Puccini+Arias

It looks like the preview branch for #1151 addresses this. I'd still like to know why. With this issue, I'm just looking for an explanation, not necessarily any code change.

**Comment by srerickson** [comment]
@banukutlu search is so much better after #1151! I think we can close this, but I'd still like to understand how the changes in that issue fixed things.

**Comment by nicktiberi** [comment]
Seems like #1151 fixed this issue — incorrect escaping was causing search to break, producing unexpected/irrelevant results.
