### ISSUE TITLE
RMD Integration

### ISSUE THREAD

**Issue by DanCoughlin** [psu-libraries/scholarsphere#12]
ScholarSphere will be the source for Open Access copies of journal article, with the Researcher Metadata Database (RMD) having a listing of all citations for articles by PSU authors. When someone uploads an OA article to ScholarSphere, we need a way to provide a link to that article to the Metadata DB so it is aware there is an OA copy.

## TODO

- [x] API endpoint for DOIs #930

**Comment by srerickson** [comment]
Is this 4.1 feature?
