### ISSUE TITLE
Adding a draft work to a collection fails silently

### ISSUE THREAD

**Issue by srerickson** [psu-libraries/scholarsphere#1211]
# Bug Report

## Description
When adding a work to a collection, draft works are included in the "Add works to collection" search results, however selecting them errors silently (there is a `500 server error` reported in the browser console). We should either support draft works in collections (preferred) or notify the user that the work cannot be added because it is a draft.

## To Reproduce
1. go to a collection's update works page
2. search for a work that is a draft and click to add it to the collection

## Expected behavior
- draft work is added or user notified of problem

**Comment by rschenk** [comment]
@srerickson It's pretty easy to fix the 500 error. You said that you would prefer to allow drafts to be added to collections, that's actually not a problem, but it becomes a little more tricky to display those drafts on the public view of the collection page. We have a few options:
* Add the draft to the collection, show that draft on the "update collection" form, but hide the draft from the public's view of that collection until the draft is published. (this is the current behavior after the 500 is fixed)
* Add the draft to the collection, show that draft on the "update collection" form, but on the public view of the collection will test every work in the list to see if the current user has view permissions
* Add draft to collection, show it on the update collection form, also show the draft on the public view of the collection, but you can't click on it unless you have the rights to.

**Comment by rschenk** [comment]
Also I should point out that, as the system currently behaves, only admins can even attempt to add draft works to collections. If you are a non-admin, searching for a draft work in the "add works to collection" box yields nothing. 

BTW in both this comment and the previous, I'm not saying iT HaS tO wOrK one way or the other, I'm just stating how the system currently behaves so we can decide how to make it

**Comment by srerickson** [comment]
I'm okay with the default behavior:
> Add the draft to the collection, show that draft on the "update collection" form, but hide the draft from the public's view of that collection until the draft is published. (this is the current behavior after the 500 is fixed)

I'm not sure I understand why only admins see drafts. This seems like it would be a generally useful feature (i.e., so you can add something to a collection before it's published). Is it hard to change? Are there reasons not to change it?

**Comment by rschenk** [comment]
For posterity, Seth, Nick, and I decided we would simply fix the 500 error in this ticket, then Seth will write up additional tickets for fixing the draft work searching and viewing permissions
