### ISSUE TITLE
Improve how we count downloads

### ISSUE THREAD

**Issue by srerickson** [psu-libraries/scholarsphere#1222]
# Feature Request

The downloads metrics for ScholarSphere 4.0 are much higher than they were for ScholarSphere 3.0. This may be because we're not doing a good job of filtering "robot" downloads. We might consider taking session information into account like we do for view counts.

**Comment by nicktiberi** [comment]
An initial step here is to investigate if there is a discrepancy in how we are treating bots/sessions in the download counting vs view counting code. If we are not taking bots/sessions into accounts for download tracking, we probably should be.

Longer term, it would be nice to expose some of the header information from the download (and view?) requests to an external analytics platform so we can capture more data about the source of the downloads.

**Comment by nicktiberi** [comment]
Add `rel=nofollow` to the download links to cut down on crawler downloads (captured in #1230).

**Comment by rschenk** [comment]
It is definitely true that we count work views and downloads differently. [Views for Works/Collections/WorkVersions](https://github.com/psu-libraries/scholarsphere/blob/04a7407fcb8408a3453f5c04f45061e64b700de2/app/controllers/resources_controller.rb#L16-L20) are "deduped" by a [cache](https://github.com/psu-libraries/scholarsphere/blob/main/app/services/session_view_stats_cache.rb) that we store in Redis that contains the resource and the users session. This same cache is [not present](https://github.com/psu-libraries/scholarsphere/blob/04a7407fcb8408a3453f5c04f45061e64b700de2/app/controllers/downloads_controller.rb#L8) on the downloads.

However, having looked at this code just now, _there is actually a bug in that cache_ that could be undercounting the Works/Collections/Versions! That cache uses only the resource's primary key, without also using the resource's type. That means if someone views Collection#1 and WorkVersion#1, the cache that was set by the collection will hit on the work version, thus undercounting the workversion.

My proposed solution to both of these issues is to add the resource type the SessionViewStatsCache, fixing the undercounting bug, and then add that stats cache to the downloads controller. I'm not sure if that will fix all the strangeness but it will help fix two obvious issues
