### ISSUE TITLE
Add rel=nofollow to download links

### ISSUE THREAD

**Issue by nicktiberi** [psu-libraries/scholarsphere#1230]
# Feature Request

## Describe the solution you'd like
Add `rel="nofollow"` to download links for files to prevent search engines/crawlers/etc from hitting these links and skewing our true download stats.

## What does "done" look like?
All file resource download links will have the `rel="nofollow"` attribute set.

<img width="939" alt="Screen Shot 2022-02-14 at 9 59 51 AM" src="https://user-images.githubusercontent.com/639920/153888455-ff05afea-aa0b-47ea-b5d7-35ed644cf001.png">

**Comment by srerickson** [comment]
@whereismyjetpack, it would be interesting to see how this change affects our metrics. We should try to look into this about a month after it is released.
