### ISSUE TITLE
It shouldn't be possible to create a work that is a collection

### ISSUE THREAD

**Issue by srerickson** [psu-libraries/scholarsphere#1234]
# Feature Request

Collections and works are mutually exclusive categories, however "Collection" is also a work type option. I think this is for historical reasons. We should remove the Collection work type and set existing works using this type to "Project".

**Comment by nicktiberi** [comment]
For the record, there are currently 4 works in production that have work type `Collection`:

- https://scholarsphere.psu.edu/resources/d5bec037-8d72-4114-a8ae-412f37a6d706
- https://scholarsphere.psu.edu/resources/18c2577a-6901-4570-addc-fc31e6de626d
- https://scholarsphere.psu.edu/resources/bb7bc33b-ee6a-4f03-8552-04cd0ba56fef
- https://scholarsphere.psu.edu/resources/2ac6a143-9618-4718-b6ec-7f52a1b810ca
