### ISSUE TITLE
Improved work/version lifecycle timestamps

### ISSUE THREAD

**Issue by srerickson** [psu-libraries/scholarsphere#1255]
# Feature Request

With our existing timestamps, there's no way to sort submissions by when the current version was "published". (This refers to the [`published` state](https://github.com/psu-libraries/scholarsphere/blob/3f45a4b594c287230528a077a3b6aa1c077e8816/app/models/work_version.rb#L185) of a work version, not the `published_date` metadata field. It's confusing - I'm sorry). 

In addition to `created_at` and `updated_at`, we currently include the following "life cycle" timestamps in the data models for works and versions:
- Work's `deposited_at`: This timestamp is badly named. It is like `created_at` but in a separate field so that we can migrate content to new versions of ScholarSphere and not worry about preserving the old `created_at` values. For older deposits (from ScholarSphere 3.0), this is simply the datetime when the deposit was created/published. For works created with ScholarSphere 4.0, `deposited_at` should be the same as `created_at`.
- Work's `deposit_agreed_at`:  The intention of this timestamp is to refer to the time when a user *first* agreed to the deposit agreement indicated in `deposit_agreement_version`. If we update the deposit agreement and user publishes a new version of a work (they agree to the new version of the agreement) then this timestamp is updated. For reference, the code is [here](https://github.com/psu-libraries/scholarsphere/blob/b2a84e22ecdb8eff524b52fc2a5095b5282809f8/app/models/work_version.rb#L185).

No lifecycle timestamps are stored at the Work Version level which means we don't track when a version was published. To address this, we should:

- [x] Confirm that we can extract last state change datetimes for all work versions from Papertrail.
- [x] create `{state}_at` timestamps on the work version that are updated when the `aasm_state` field is set/updated. If a version is published, the `published_at` field is updated; if withdrawn, the `withdrawn_at` field is updated; etc.
- [x] Populate this field using information from Papertrail. (see step 1)

**Comment by rschenk** [comment]
Just some notes from my investigation:

All of this information is stored in PaperTrail and it will be pretty trivial to get it out for the purposes of backfilling.

The library that we use to model the WorkVersion's state machine (`draft -> published -> withdrawn -> removed`) automatically provides a [timestamping functionality](https://github.com/aasm/aasm#timestamps) out of the box, which we are not currently using but would be trivial to enable. Basically all we have to do is add a field called `published_at` and it will automatically get set when the WorkVersion is published—and not be modified if that version is withdrawn or reverted to a draft. This behavior is different to @srerickson's description above but I think it's superior (and I'm guessing that Seth specified the above for perceived ease of implementation).

When backfilling these timestamps, we will need to come up with some rules for how migrated works from SSv3 will behave. The best algorithm I can come up with is (pseudo-code):

```
published_at = oldest(
  timestamp from PaperTrail's publication event,
  Work's deposited_at timestamp
)
```
