### ISSUE TITLE
Automatically set thumbnail_selection after Work or Collection creation

### ISSUE THREAD

**Issue by ajkiessl** [psu-libraries/scholarsphere#1281]
If a Work or Collection has an `auto_generated_thumbnail_url` on creation, then set the `thumbnail_selection` to "auto_generated".  Otherwise, the `thumbnail_selection` will default to "default_icon".

It might also make sense to create a script that converts all `thumbnail_selections` for existing Works and Collection to "auto_generated" if an `auto_generated_thumbnail_url` is found.  It should be noted, however, that this script could overwrite the `thumbnail_selection` for a record where the user actually preferred to use the default icon over the auto generated thumbnail.  Early on, this may be very few (or zero) so it might not be a big deal.

**Comment by srerickson** [comment]
Thanks @ajkiessl! For now, I think it's great that new works will default to the auto-generated thumbnail (if available).

**Comment by ajkiessl** [comment]
@srerickson No problem.  Your comment reminded me that I didn't add a rake task to update existing Works and Collections to use the auto-generated thumbnail if one exists.  I added that now, in case we want to run it after the rollout next week.
