### ISSUE TITLE
Administrator can assign a curator to a work

### ISSUE THREAD

**Issue by EricDurante** [psu-libraries/scholarsphere#1443]

**Comment by bdezray** [comment]
Enable the ability to assign an individual as a curator to a deposit directly within the system. This information should be stored internally, accessible to administrators and curators, but not displayed publicly. 

- [x] Modify the database schema to include a field for curator assignment associated with each deposit.
- [x] Add a new option in the admin view of works to assign a curator
- [x] Define appropriate permissions for admins to access and modify curator assignments
- [x] Audit trail for curator assignments

**Comment by Smullz622** [comment]
> * [ ]  Modify the database schema to include a field for curator assignment associated with each deposit.

@bdezray I'm still learning the scholarsphere terminology/structure, does deposit exclusively apply to works or does this need to be added to collections as well?

**Comment by bdezray** [comment]
@Smullz622 My bad! I should be consistent with terminology here. We curate right now at the work level, so we would only need it applied to works and not to collections. However, we may want it applied on the project level if that is implemented.

**Comment by Smullz622** [comment]
@bdezray thanks! Follow up- is there a scenario when there would be more than one curator assigned to a work?

**Comment by bdezray** [comment]
@Smullz622 Great question! Yes, but probably not at the same time. We would want to be able to transfer curation between people throughout the curation process. For the main purpose of the assignment of enabling notification, the most important information would be who is currently assigned, but we likely would want to keep a log of who all has worked on curation for a work.
