### ISSUE TITLE
Develop custom forms for each pathway

### ISSUE THREAD

**Issue by bdezray** [psu-libraries/scholarsphere#1461]
# Feature Request
Dynamically display metadata fields and their validation by pathway.

**Comment by bdezray** [comment]
The General pathway should maintain the current deposit process. The Scholarly Works pathway and the Data & Code pathway are described in the following issues:

- #1467 

- #1469

**Comment by EricDurante** [comment]
Closing this because it is essentially a sub-epic of https://github.com/psu-libraries/scholarsphere/issues/1153, and the form customization work from the current backlog has been completed.
