### ISSUE TITLE
OA Article Pathway: RMD Connection

### ISSUE THREAD

**Issue by bdezray** [psu-libraries/scholarsphere#1462]
# Feature Request
Ideally, metadata fields that RMD has information for could be autofilled. 

- [ ] Send request for metadata based on DOI and/or title search (may need to leave this option to a future development time depending on difficulty)
- [ ] Auto-fill metadata fields and disable editing of DOI and Title

**Comment by ajkiessl** [comment]
@bdezray There are a couple issues with getting permissions data (publisher statement, embargo date, and license).  The permissions data is only stored with Activity Insight OA Files in RMD and is not supplied through the API.  Here's a little more info on Activity Insight OA File process: https://github.com/psu-libraries/researcher-metadata?tab=readme-ov-file#activity-insight-open-access-post-print-publication-file.  That data is also dependent on whether the file is the Accepted Version or the Published Version.  We have three ways to determine the file's version in RMD.  One: a little NLP tool we built to analyze the text in the file to try to find indicators of either version.  This is not 100% accurate and often is not able to determine the version.  This tool is used in both the Activity Insight OA File upload process and the regular upload to ScholarSphere process in RMD.  Two:  Admins manually determine the version of the file.  This is done only during the Activity Insight OA File upload process.  Three: The depositor determines the version.  This is done in the regular upload to ScholarSphere process.  Once the version is known, we can pull permissions data from Open Access Button.

We could try to implement a similar process to the upload to ScholarSphere process in RMD within ScholarSphere.  This might look something like: when the user submits their files, the NLP process runs to try to determine the version.  Then, the depositor is directed to a step to confirm the version.  When that form is submitted, the system calls out to the Open Access Button to pull and store the permissions data.  I can set up RMD's QA instance to let you test out submitting an OA publication there.

I think if we want to do this, it will be a bit of a project on it's own.  It might even be worth pulling some that code out of RMD and putting it into it's own package to be shared between systems.

**Comment by ajkiessl** [comment]
Ignoring publisher statement/permissions data for now.

**Comment by bdezray** [comment]
@ajkiessl Here is the help text for the RMD DOI search:

By adding your publisher identifier (e.g., DOI) to this field, we can search the Penn State Researcher Metadata Database and potentially enrich the following metadata fields for your deposit. If the Researcher Metadata Database contains pertinent information about your scholarly work, it will automatically be imported into the fields below. You can choose to retain or modify this imported information. 

Please note that if you are working to make your work open per [AC02](https://policy.psu.edu/policies/ac02), we recommend using the process available directly within the [Researcher Metadata Database](https://openaccess.psu.edu/deposit/rmd/) for deposit when possible.

**Comment by bdezray** [comment]
A few additional requested updates after Ana reviewed the process as well:
(1) Can we update the help text to say: "By adding the Digital Object Identifier (DOI) for the article, issued by the Publisher, to this field, ...
(2) Can we also add the following sentence to the bottom of the first paragraph of the help text: "You cannot modify the DOI once you have completed a search. If you discover that the DOI is incorrect, please delete the draft and start a new search."
(2) For the "Publisher" Field, can we import information from "Journal" or "Journal Title" instead of "Publisher name"?
(3) Would it be possible to not map RMD's URL field into the related URL field in ScholarSphere? There appear to be some oddities to it that we would like to not use for now. 
(4) It looks like the title can change from what a user enters on the Work Type page if it is different in RMD. Would it be possible to also display the title on the Work Details page or create a warning if the title has changed?
