### ISSUE TITLE
Dataset Pathway: User initiated data curation request prior to publication

### ISSUE THREAD

**Issue by bdezray** [psu-libraries/scholarsphere#1463]
# Feature Request
Provide users with an option to request curation prior to publication while still in draft state. This could be displayed on the final review page as an option. Selection of this option would need to trigger an entry in AirTable.

**Comment by Smullz622** [comment]
Update of WDLL

- [x] make this a 'Request Curation & Save' button that appears in the following conditions:
        - on the 'Review & Publish' tab of the form
        - work is a "dataset" or "software or program code" type
        - curation has not already been requested

- [x] If curation has already been requested, disable the publish button
- [x] Have a 'Request Curation' section at the bottom of the form that provides guidance for that button (see below)
- [x] In addition to fields we already send to Airtable, add a label marking the record as 'Curation Requested' in the Airtable export

Help Text (@bdezray please edit as needed)
If curation has not yet been requested: 
"Please select 'Request Curation & Save' below if you would like data curation on your work before it is published."

If curation has already been requested: 
"Curation has been requested. We will notify you when curation is complete and your work is ready to be published."

**Comment by EricDurante** [comment]
@Smullz622 
I noticed that there are a few additional notes on https://github.com/psu-libraries/scholarsphere/issues/1469 about the data curation request feature. I'm just bringing it to your attention in case there's anything else there that you need to consider for this ticket.

**Comment by bdezray** [comment]
@Smullz622 Below I have outlined text for the curation request:

Select 'Request Curation & Save' below if you would like ScholarSphere curators to review your work assessing its findability, accessibility, interoperability, and reusability prior to publication (recommended).
 
If curation has already been requested:
"Curation has been requested. We will notify you when curation is complete and your work is ready to be published. If you have any questions in the meantime, please contact ScholarSphere curators via our [contact form](https://scholarsphere.psu.edu/incidents/new).


I was also wondering if it would make sense to include a description here for the type of curation that occurs if they click publish. Let me know if you think this would fit better in this section or in the pop-ups.

Select 'Publish' if you would like to self-submit your deposit to Scholarsphere and make it immediately public. ScholarSphere curators will review your work after publication. Note, because curatorial review occurs after publication, any changes or updates may result in a versioned work.

**Comment by Smullz622** [comment]
@bdezray Thanks! 

I think the publish description would be great to include in this section as well. That way users have an informed choice before clicking either 'Request Curation' or 'Publish'
