### ISSUE TITLE
Curator initiated contact to depositor

### ISSUE THREAD

**Issue by ajkiessl** [psu-libraries/scholarsphere#1464]
Ideally, this process would enable autogenerated information from ScholarSphere to be entered into the "Create a Ticket Initiated by You (System)" in LibAnswers. Some information can be pulled directly from the ScholarSphere deposit into the "Create a Ticket Initiated by you (System)" form, while others need to be supplemented with other information:
| LibAnswers Field | ScholarSphere Field |
|------------------|---------------------|
| Send to (name) | Depositor Name (directly from ScholarSphere) |
| Send to (email) | Depositor Email (directly from ScholarSphere) |
| Subject | Insert "Work Title" into fillable email subject line (Supplemented with info directly from ScholarSphere) |
| CC Email to | Creator and Editor Emails (directly from ScholarSphere) |
| Email Message | Message from curator which needs to be generated somewhere either in ScholarSphere or LibAnswers |

**Comment by ajkiessl** [comment]
Not sure if this will do the trick.  From the documentation:


>Pass additional parameters in the chat widget link

>You can also append additional query string parameters to the direct link for a chat widget to pass known data about the patron into the resulting chat exchange. These are generally used by sites who are custom coding their own scripts to help pass these details into the chat exchange from a third party communication tool (like a chatbot).

>Available parameters:

>    question: fills in the initial question field.
>    patron_name: fills in the patron name field.
>    patron_email: fills in the patron email field.
>    referer: include the referring URL.
>    referer_title: include the referring URL title.

From: https://ask.springshare.com/libanswers/faq/1782

**Comment by ajkiessl** [comment]
Ah actually I'm seeing they have an API.  There's a create ticket endpoint: https://ask.springshare.com/libanswers/faq/1669

This is probably what we want.

**Comment by ajkiessl** [comment]
@bdezray Could you clarify what is meant by "Creator and Editor Emails" for the "CC Email to" field?  Is Creator the admin user creating the ticket?  Is Editor the users with edit access to the work?

**Comment by bdezray** [comment]
@ajkiessl Creator would be all users listed as Creators (these are added under the contributors tab) and yes, editors are the users with edit access to the work.

**Comment by ajkiessl** [comment]
~~Cannot complete the "CC Email to" field yet.  Details here: #1485~~

This is moot

**Comment by ajkiessl** [comment]
@bdezray Since the LibAnswers API only creates tickets like the "Originated from Patron" form, we could potentially create a ticket through the API by only passing the patron's name, patron's email, and a subject.  Then direct the admin right to the ticket in LibAnswers to fill in the message and manually add CC'd emails.  This would look a bit awkward to the patron though, I think.  Here's how the first email sent to the patron would look after submitting the form in LibAnswers:
![Screenshot 2024-02-16 at 10 36 13 AM](https://github.com/psu-libraries/scholarsphere/assets/32677188/a57fb228-f9a5-4506-84e5-83564211ca77)

Where I (Alex Kiessling) am the admin contacting the patron, and the "test" in the Original Question is the subject.  The message would look like a reply to the patron (even though this would be the first time the patron is seeing this).  This might be confusing, or maybe not.  Does this sound like a usable workaround for now?

Also, this might not be intuitive to admins.  So, I'll need to add some help text to explain that submitting the form in ScholarSphere will not send an email to the patron and that the admin must complete the submission in LibAnswers.

We could also automatically create the subject and skip the form in ScholarSphere altogether.

**Comment by bdezray** [comment]
@ajkiessl Thank you for thinking through all of this! I think the ideal solution was what you proposed to SpringShare, but if it isn't too complicated in the meantime using this workaround where the subject line is auto-generated to be: ScholarSphere Deposit Curation: [title from ScholarSphere work] and the admin is directed straight to LibAnswers would work. However, if this workaround is time consuming, we may be better waiting for SpringShare to update the API.

**Comment by ajkiessl** [comment]
@bdezray Ok, I'll get to work on this.  It shouldn't be time consuming.  It's more of a 3/4 baked solution (and I've already written most of the code) rather than a workaround.  When SpringeShare updates their API, it would just be a matter of extending the code and maybe a few tweaks.
