### ISSUE TITLE
Customized forms for the Scholarly Works Pathway

### ISSUE THREAD

**Issue by bdezray** [psu-libraries/scholarsphere#1467]
Fields for this pathway are listed below. In our current set up the creators are added in their own form and the embargo date occurs during the work settings. It may be useful to consider moving the embargo setting somewhere in the deposit form. Additionally, we would like to prevent ScholarSphere DOI minting for records that have a publisher identifier (DOI).
Work Title (Required)
Work Type (Required)
Description (Required)
Publication Date (Required)
Subtitle (Optional)
Publisher's Statement (Optional)
Keyword(s) (Optional) -> Does RMD pull keywords?
Publisher (Optional)
Publisher Identifier (DOI) (Optional)
Related URLs (Optional)
Subject (Optional)
Language (Optional)
Creator (Required)
Depositor (Required)
Embargo Date (Optional)
License (Required)

**Comment by EricDurante** [comment]
@bdezray You listed both Publisher's Statement and Set Statement above. Are those not the same thing?

**Comment by bdezray** [comment]
@EricDurante I just confirmed with Ana that yes those are the same thing.

**Comment by EricDurante** [comment]
> Additionally, we would like to prevent ScholarSphere DOI minting for records that have a publisher identifier (DOI).

@bdezray What does it mean in this context for a record to have a publisher identifier? Does that just mean that if the depositor has entered a value in the "Identifier" field for the work version, then we shouldn't mint a DOI? Or do we have some other way of finding out if the work already has a DOI?

**Comment by EricDurante** [comment]
@bdezray Sorry, I've hit another point of confusion with regard to DOIs. I see that it's possible in ScholarSphere for a work to have a DOI _and_ for each version of the work to have a different DOI. It looks as though the act of minting a DOI in ScholarSphere only creates a DOI for the work.

Assuming that what I've said already is correct, I'm wondering where exactly we should look for publisher DOIs when determining whether or not to allow the user to mint a DOI for a work. Should we disallow minting if _any_ version of the work has been provided with a publisher DOI? Or only if the _latest_ version of the work has been?

Is there anything else that I might be missing here?

@rschenk Do you have any insight into how this part currently works and/or how things should work after this change?

**Comment by EricDurante** [comment]
@bdezray 
I think that the changes to the forms and validations that comprise the bulk of this issue can stand on their own as a feature, and I don't want them to be blocked from review/release due to the other features/changes described in the issue, so I've split those changes out into two other separate tickets:

- https://github.com/psu-libraries/scholarsphere/issues/1486
- https://github.com/psu-libraries/scholarsphere/issues/1487

I think that each of these can be developed and released independently of each other as well.

Does that sound good to you? If so, I think that this can be shipped.

**Comment by bdezray** [comment]
@EricDurante Yes, I think breaking these two other issues make sense to stand on their own. Thank you for making those tickets! 

As for the DOI minting, I vaguely remembered us talking about version level DOIs but wasn't sure if that was implemented. Maybe this is something we can discuss? But I think ultimately what we want is ScholarSphere DOI minting to be blocked if the publisher DOI field (which I believe is currently separate from the DOI field where ScholarSphere DOIs end up) is filled with a valid DOI in the latest version.
