### ISSUE TITLE
Display citation for datasets & code on work page

### ISSUE THREAD

**Issue by bdezray** [psu-libraries/scholarsphere#1472]
# Feature Request
We would like to have the citation display on the work page for datasets & code. This will require pulling metadata for title, creators, and DOI and adding ScholarSphere as the publisher. Here are some examples at other repositories:

[Dryad](https://datadryad.org/stash/dataset/doi:10.5061/dryad.sd7cd06)
[Zenodo](https://zenodo.org/records/10606425)
[Figshare](https://figshare.com/articles/dataset/Shortening_and_asthenospheric-flow_driven_Miocene_vertical-axis_rotations_of_the_NE_Qaidam_Basin_northern_Tibetan_Plateau/25144715)

**Comment by Smullz622** [comment]
@bdezray I have a couple assumptions, could you confirm?

- Citations should be in APA format
- We want to include the 'copy to clipboard' button found in the examples

**Comment by bdezray** [comment]
@Smullz622 Thanks for checking in on this! 

- Citation format: I think that APA makes sense, unless we are able to use something like the (DataCite Citation Formatter)[https://support.datacite.org/docs/datacite-citation-formatter]
- A copy to clipboard button would be ideal if it isn't too complicated.
