### ISSUE TITLE
Remove ScholarSphere Updates from Homepage

### ISSUE THREAD

**Issue by bdezray** [psu-libraries/scholarsphere#1473]
# Feature Request
Remove ScholarSphere Updates from Homepage and replace with search bar across the top.

**Comment by bdezray** [comment]
If we end up not removing entirely, here is some language to update the update:

We have released a new version of ScholarSphere! The new platform includes deposit pathways for scholarly works as well as datasets and code. We’ve also added the ability to request curatorial review prior to publication, view dataset and code citation information, and access publication metadata via the Researcher Metadata Database. [Read more about ScholarSphere. ](https://scholarsphere.psu.edu/about)

Anything missing?

**Comment by Smullz622** [comment]
@bdezray It looks like either are very easy fixes. To be clear, the preference to remove it, correct?
