### ISSUE TITLE
Help text for buttons at bottom of work deposit form and publication warning

### ISSUE THREAD

**Issue by bdezray** [psu-libraries/scholarsphere#1477]
Add help text that describes the what action will occur by clicking each button when hover over button. It would also be helpful to add a before you publish warning similar to the attached. 
[Mendeley_Data_Before_You_Publish_Screenshot.docx](https://github.com/psu-libraries/scholarsphere/files/14166774/Mendeley_Data_Before_You_Publish_Screenshot.docx)

**Comment by bdezray** [comment]
Move depositor agreement to the publication and/or request curation pop up

**Comment by bdezray** [comment]
@jlandiseigsti 
Save and Exit: Save your draft. It will be accessible via your dashboard and visible only to you and those with edit access.
Save and Continue: Save your draft and proceed to the next section of the deposit form.
Cancel: Discard changes and return to the work's display page.
Delete Draft: Permanently delete the draft.
Publish: Publish your work to make it publicly visible. Changes cannot be made to the published version, but you can create a new version if updates are needed.

**Comment by jlandiseigsti** [comment]
Would you also like any help text on "Finish" or "Request Curation"?

**Comment by bdezray** [comment]
@jlandiseigsti 
Help Text (tooltip) on buttons
o	Request Curation: Save your work as a draft and submit it for curatorial review. 
o	Request Accessibility Remediation: Save your work as a draft and submit it for accessibility review and remediation. 

Publish dialog modal
•	Heading: Ready to Publish?
•	Description Text: By selecting Publish, you are making your work publicly accessible. This means it will be broadly discoverable and downloadable (unless an embargo is applied). Once a version is published, it cannot be modified. However, you can create a new version to make changes, and the new version will supersede previous ones. Older versions will remain accessible unless they are specifically withdrawn or deleted by repository managers upon reasonable depositor request. 

If you are ready to proceed, please confirm the acknowledgments below:

•	Additional check box(es) for agreements
o	I have read and agree to [the deposit agreement](https://scholarsphere.psu.edu/agreement).
o	I confirm that this deposit was produced or sponsored by at least one member of the Penn State community.
o	I confirm that this deposit meets the requirements of [Penn State Policy AD69 Accessibility of Electronic and Information Technology](https://policy.psu.edu/policies/ad69) or that I will actively work with curators to ensure compliance. 
o	I confirm that the deposit does NOT contain information with a Sensitive Information Classification of Moderate (Level 2) or higher according to [Penn State Policy AD95 Information Assurance and IT Security](https://policy.psu.edu/policies/ad95). 
•	I like the language for request curation and cancel and only think that cancel needs a tool tip. 
o	Cancel: Return to the Review & Publish Page.

Request Curation Dialog Modal
•	Heading: Ready to Send for Curation?
•	Description Text: By selecting Request Curation & Save as Draft, your draft work will be submitted to the ScholarSphere Curation Team for review. Once approved by a curator, the work will be published, and if applicable, a DOI will be minted. 

If you are ready to proceed, please confirm the acknowledgments below:

•	Additional check box(es) for agreements
o	I have read and agree to [the deposit agreement](https://scholarsphere.psu.edu/agreement).
o	I confirm that this deposit was produced or sponsored by at least one member of the Penn State community.
o	I confirm that this deposit meets the requirements of [Penn State Policy AD69 Accessibility of Electronic and Information Technology](https://policy.psu.edu/policies/ad69) or that I will actively work with curators to ensure compliance. 
o	I confirm that the deposit does NOT contain information with a Sensitive Information Classification of Moderate (Level 2) or higher according to [Penn State Policy AD95 Information Assurance and IT Security](https://policy.psu.edu/policies/ad95). 
•	I like the language for request curation and cancel and only think that cancel needs a tool tip. 
o	Cancel: Return to the Review & Publish Page.

Request Remediation Dialog Modal
•	Heading: Ready to Send for Accessibility Remediation?
•	Description Text: By selecting Request Accessibility Remediation, your draft work will be submitted to the Adaptive Technologies Team. Once remediation has been completed, the work will be published. 

If you are ready to proceed, please confirm the acknowledgments below:

•	Additional check box(es) for agreements
o	I have read and agree to [the deposit agreement](https://scholarsphere.psu.edu/agreement).
o	I confirm that this deposit was produced or sponsored by at least one member of the Penn State community.
o	I confirm that this deposit meets the requirements of [Penn State Policy AD69 Accessibility of Electronic and Information Technology](https://policy.psu.edu/policies/ad69) or that I will actively work with curators to ensure compliance. 
o	I confirm that the deposit does NOT contain information with a Sensitive Information Classification of Moderate (Level 2) or higher according to [Penn State Policy AD95 Information Assurance and IT Security](https://policy.psu.edu/policies/ad95). 
•	Buttons should be Request Accessibility Remediation or Cancel. No help tip needed to the Request Accessibility Remediation since a description will be above. 
o	Cancel: Return to the Review & Publish Page.
