### ISSUE TITLE
Move embargo date from work settings to main create/edit form

### ISSUE THREAD

**Issue by EricDurante** [psu-libraries/scholarsphere#1486]
Currently a work cannot be embargoed until after it is created/published since the embargo date field does not appear in the series of forms used to create the work. It would make more sense for a depositor to be able to set an embargo date as the work is being created.

Open questions:
- Do we know why it was designed this way in the first place? Was it done purposefully for a reason that we haven't considered?
- After we make the change so that a work can be created with an embargo date, should the workflow for changing/removing the embargo date remain as is (in the work settings)? Or should this instead be done in the metadata/file editing workflow also?

**Comment by Smullz622** [comment]
To answer question 1: I looked back into old tickets, and it seems like it was done this way so users could change the embargo without having to create a new version (#621 and #601).

**Comment by EricDurante** [comment]
> To answer question 1: I looked back into old tickets, and it seems like it was done this way so users could change the embargo without having to create a new version

Ah, yes! That makes a whole lot of sense. I thought that there had to be a good reason. So we'll definitely want to keep the ability to edit the embargo in the work settings. For me, that actually clarifies the whole reason why the "work settings" are a separate thing from editing all of the rest of the work data. Thanks so much for digging that up @Smullz622!
