### ISSUE TITLE
DOI minting for the Data & Code Pathway

### ISSUE THREAD

**Issue by EricDurante** [psu-libraries/scholarsphere#1492]
> DOI minting is on the work settings page, but it might be nice to have the request for DOI minting be during the deposit process or be displayed as recommended just after publication. We also should require DOIs to be minted by ScholarSphere.

Open Questions:
- How exactly should this behave?

**Comment by bdezray** [comment]
I think an ideal set up would be to have data &code pathway users be redirected to the work settings page after successfully publishing and having the DOI field be recommended for this pathway.

**Comment by ajkiessl** [comment]
## WDLL

Another optional field at the final step of the work upload process for a user to opt in to have their DOI minted when published.  Similar to the request curation, but in this case there will be a boolean field (maybe a checkbox).  This field could be right after the request curation field: 



![Image](https://github.com/user-attachments/assets/1d65bfea-dfde-46f6-8e6d-afc69c60929c)



The actual minting of the DOI should not happen until the submission is published.  So, if they save it as a draft, the DOI should not be minted yet.  Also, as the title of the issue states, this should be for the Data & Code pathway (and soon to include instruments).

Refer to `app/controllers/dois_controller.rb` to see how DOIs are currently being minted.

**Comment by bdezray** [comment]
@Smullz622 Here is the help text:

A Digital Object Identifier (DOI) is a unique identifier that ensures your work can be easily cited and reliably located. We recommend minting a DOI unless your work already has one from another publisher or repository. 

_Note: It may take a few moments for the DOI to be minted after publication. Please refresh the page if it does not appear right away and do not request an additional one._
