### ISSUE TITLE
Develop a Pathway for Graduate Degree Culminating Experiences

### ISSUE THREAD

**Issue by bdezray** [psu-libraries/scholarsphere#1582]
Description:
Create a new pathway specifically for graduate degree culminating experiences. This pathway will involve creating a new work type for professional doctoral culminating experiences, modifying existing work types, and implementing specific controlled vocabulary and metadata fields.

Requirements:

- [x] Create a New Work Type: Professional Doctoral Culminating Experience

- This new work type should be added to the system to support the pathway.

- Additionally, the existing "Masters Culminating Experience" work type should also feed into this new pathway.

- [x] Hide Specific Work Types from Selection

> The following work types should no longer be selectable options in the system:

- Capstone Project

- Dissertation

- Masters Thesis

- [x] Include the Following Work Details for Each Work Type:

1.  **Sub-Work Type**

- For Professional Doctoral Culminating Experience (Controlled Vocabulary):

> - Integrative Doctoral Research Project

> - Praxis Project

> - Culminating Research Project

> - Doctor of Nursing Practice Project

> - Public Performance

> - Capstone Project

- For Master's Culminating Experience (Controlled Vocabulary):  

> - Scholarly Paper/Essay (MA/MS)

> - Capstone Project

> - Capstone Course Work Product

2. **Graduate Program:** Retrieve the controlled vocabulary list from Graduate School or ETDA. Required.
3. **Degree:** Retrieve the controlled vocabulary list from Graduate School developers or ETDA. Required.
4. **Description:** Free text field for a brief description of the work. Required. 
5. **Publication Date:** The publication date. Required.
6. **Publisher:** Defined to Penn State ScholarSphere.
7. **Keyword:** Tags or keywords related to the work.
8. **Related URLs:** Links to related works or resources.
9. **Language:** Language in which the work is written.
- [x] Ensure that the following elements function the same as in the scholarly works pathway:

- Work Type
- Contributors
- Files upload

**Comment by ajkiessl** [comment]
Allow DOI minting on submission for these work types.
