### ISSUE TITLE
Include the word "Archives" as a tag line or in the SS description

### ISSUE THREAD

**Issue by binkylush** [psu-libraries/scholarsphere#1599]
For accessibility reasons, we need to indicate that SS is an archive of PSU research. @bdezray - do you have suggested wording? Thanks!

**Comment by bdezray** [comment]
Add the following tagline language to the Blue Bar that says Welcome to ScholarSphere as a subtitle as well as replace the "A service of the University Libraries" in the bottom left with this language. 

An institutional repository and archive dedicated to sharing and preserving Penn State’s scholarly and research outputs
