### ISSUE TITLE
Create a form to request an alternate format of a work.

### ISSUE THREAD

**Issue by binkylush** [psu-libraries/scholarsphere#1600]
Create a form that will:

1. be linked to from every work page
2. capture the url of the work
3. capture the email of the user if logged in. If not logged in, user should be able to add their email
4. provide text field for the user to describe what they need.
5. ~~form should submit to ul-digital-accessibility@lists.psu.edu~~

**Comment by ajkiessl** [comment]
It would be nice if we could just direct users to this form: https://libraries.psu.edu/about/accessibility/request-accommodation-accessibility-help with the work url automatically added to the "your question" section.  This may not be possible, though, but it's something to look in to.

**Comment by ajkiessl** [comment]
Another way to do this would be to use LibAnswers.  We could create an "accessibility" queue and in ScholarSphere direct to a form that passes over the necessary metadata about the work to LibAnswers and create a ticket there.

**Comment by ajkiessl** [comment]
### WDDLL

Ideally, we'd like a link for each file on a work's show page that says "Request an alternate format".  This should direct to a libanswers form with the fields mentioned in the original post.  A link to download the file should be passed to the libanswers form if possible.

We need to get the accessibility queue set up in libanswers and a form created before coding this up.

For reference, catalog passes some parameters to a custom libanswers form via the "Ask a Librarian" button.
