### ISSUE TITLE
Ability for Depositor to Save Work Draft and Request Accessibility Remediation Assistance

### ISSUE THREAD

**Issue by ajkiessl** [psu-libraries/scholarsphere#1603]
From the epic (https://github.com/psu-libraries/scholarsphere/issues/1589):

>Similar to how depositors can currently request curation assistance for datasets prior to publication, we may want depositors of articles and other work types to have the ability to do the same thing in order to request manual review/assistance from a ScholarSphere curator regarding document accessibility prior to publishing their work. If a depositor selected this option, their work would be saved as a draft, and the work would enter a queue for review by a curator.

>Open questions:
>Does this apply to all non-data/code work types?
>Should this always be an option for the applicable work types, or should it only be an option if one or more files doesn't pass automated accessibility checking? (The latter would require us to make the depositor wait for feedback before moving on..)
>Do we want the list of these curation requests to live in AirTable along with all of the other curation tasks? If so, how should they be identified or distinguished from other tasks?

Part of #1589

**Comment by ajkiessl** [comment]
@bdezray

**Comment by Smullz622** [comment]
- This will apply to all work types. 

- The button should appear unless _all_ of the files have passed the automatic checker. This part is on hold until #1602 is complete. (Update- this will be done in #1611 )

- The button will send a record to Airtable with the label 'Accessibility Remediation Requested'. Curators will do a precheck of the files (ensuring that it actually belongs with the work, no PII, etc). Curators will notify the accessibility team- most likely via a button in work settings, but that is TBD and will be in a separate ticket.
