### ISSUE TITLE
Add admin button to send work's to accessibility queue

### ISSUE THREAD

**Issue by Smullz622** [psu-libraries/scholarsphere#1609]
We have determined that all works will be sent to Airtable first so that curators can do a precheck of the file (ensure it is the correct file, there is not any PII, etc). Curators need a way to easily notify the accessibility team that the work is ready for review/remediation. We will add a button to work settings that is only visible to admins. It will work similar to the current lib answers button to send info on the work (including auto checker results) to a different lib answers queue. 

If possible, the ticket will also cc the current curator for the work. From previous work, that may not be possible, but it's worth checking if libanswers has updated their capabilities. 

The accessibility queue has not been set up yet but will add details once it is.

**Comment by ajkiessl** [comment]
We will not be able to add CC'd emails: https://lounge.springshare.com/discussion/comment/6568#Comment_6568
