### ISSUE TITLE
 OAI-PMH endoint

### ISSUE THREAD

**Issue by srerickson** [psu-libraries/scholarsphere#183]
It would be good to have an OAI-PMH endpoint so that ScholarSphere works can be harvested by services like [Unpaywall](https://unpaywall.org/).

- [x] Create a preview branch with the [Blacklight OAI Provider](https://github.com/projectblacklight/blacklight_oai_provider) installed. Minimal configuration to start.
- [x] Test the OAI-PMH endpoint using Unpwall: https://api.unpaywall.org/repository/endpoint/test/  (Seth). 
- [x] Make adjustments to configuration.

Example of a working test for the OAI-PMH endpoint [http://serval.unil.ch/oaiprovider](https://www.google.com/url?q=http://serval.unil.ch/oaiprovider&sa=D&source=editors&ust=1645721893236489&usg=AOvVaw2RQmiyBthvgdg2kbU7BNxV) can be seen at [https://api.unpaywall.org/repository/endpoint/test/http://serval.unil.ch/oaiprovider](https://www.google.com/url?q=https://api.unpaywall.org/repository/endpoint/test/http://serval.unil.ch/oaiprovider&sa=D&source=editors&ust=1645721893236532&usg=AOvVaw3L1Pnp5uIzsCSyn0WW4Aa1)

**Comment by awead** [comment]
We might be able to use Blacklight's plugin for this https://github.com/projectblacklight/blacklight_oai_provider.

**Comment by nicktiberi** [comment]
Here's an example of this working in the ETDA Explore app: https://etda.libraries.psu.edu/catalog/oai?verb=ListRecords&metadataPrefix=oai_dc

**Comment by srerickson** [comment]
@nicktiberi , Just tried unpaywall's endpoint test with the preview branch and it looks like login is required for the preview url? Can we make it public?

**Comment by srerickson** [comment]
@nicktiberi, I did a quick review of the endpoint, and here are some changes:

- publisher identifier (doi) should be exposed as a `dc:identifier` (duplicates are ok)
- ScholarSphere's doi (on the Work) should also be exposed as `dc:identifier`
- publication date (metadata field) should be exposed as `dc:date`
- work type should be exposed as `dc:type`
 
Note: I'm using this resource as a reference: `[PREVIEW URL]/catalog/oai?verb=GetRecord&metadataPrefix=oai_dc&identifier=oai:scholarsphere.psu.edu:9e587e72-8852-4971-9a6c-9d865fc9c7f0`, which you can compare to [this](https://scholarsphere.psu.edu/resources/9e587e72-8852-4971-9a6c-9d865fc9c7f0)

**Comment by nicktiberi** [comment]
@srerickson - I pushed up some changes to the preview branch. Let me know if things are now looking more as you'd expect.

One other piece of config we may want to set is the admin email, which is currently defaulted to `nobody@localhost`. What should this be set to?

**Comment by srerickson** [comment]
thanks! We should admin email to `scholarsphere@psu.edu`

**Comment by srerickson** [comment]
@nicktiberi, sorry one more config is possible: I'd like to use the ListSets  functionality to provide feeds that are scoped to Public or Penn State works. That way, I can tell Unpaywall to only import the "Public" list. 
https://github.com/projectblacklight/blacklight_oai_provider#customizing-listsets
