### ISSUE TITLE
Ruby Sass is EOL'd

### ISSUE THREAD

**Issue by awead** [psu-libraries/scholarsphere#20]
When doing a bundle install, we get this:

```
Post-install message from sass:
  
Ruby Sass has reached end-of-life and should no longer be used.
```

As far as I can tell, this is only because we're using the asset pipeline to compile stylesheets. We could find another way to do this, or option B, ditch the AP altogether. I'm kinda leaning more in the option B direction.

In some mere 30 seconds of googling, I came across this:

https://medium.com/@coorasse/goodbye-sprockets-welcome-webpacker-3-0-ff877fb8fa79

Thoughts? I like the implementation scheme, personally, but I'm open to other ideas.

**Comment by whereismyjetpack** [comment]
I think generally speaking ditching the asset pipeline is the 6.0 way. however, depending on our dependents we might not be able to do this if they include things in the asset pipeline.

**Comment by awead** [comment]
Yeah, that seems the way to me, only Rails is shipping with AP for css assets, so I don't know. I'm trying to rectify the AP:sprockets versus Webpack:sass thing. But, if moving everything to webpack just makes the problem go away, I'm down with that.

**Comment by DanCoughlin** [comment]
First goal for this is to figure out what we are going to do in place of this, which may be just finding another SASS compiler

**Comment by awead** [comment]
We're not using ruby sass anymore because everything's in Webpack now.
