### ISSUE TITLE
Asyncronous file parsing

### ISSUE THREAD

**Issue by DanCoughlin** [psu-libraries/scholarsphere#259]
We have a couple different jobs that need to run for processing of files once they have been uploaded.

- [x] #122 FITS
- [x] #257 Full text extraction
- [x] #258 Clam AV jobs

**Comment by whereismyjetpack** [comment]
One Option:

sample code for the fits / full text extraction lives here (https://github.com/psu-stewardship/metadata-listener) and wires into the preview/clam-job branch of scholarsphere-4

scholarsphere-4 calls a stub activejob; and the listener picks it up the job. right now it just emits the text to screen

Another option: 

run all of this in the same scholarsphere codebase, allowing the activejobs to be run with the same app, and then we'd run the async jobs in production much like we do the shine promotion job now -- we'd call the scholarsphere app with a different set of parameters.
