### ISSUE TITLE
Versioning Works

### ISSUE THREAD

**Issue by srerickson** [psu-libraries/scholarsphere#30]
This is an issue for discussing work versioning logic. See previous discussion [here](https://github.com/psu-stewardship/scholarsphere/issues/1623).

**Comment by srerickson** [comment]
## Metadata that __cannot__ change between versions

- Visibility Settings: It should not be possible for one version of a work to be public while another version is "PSU only". That would mean different users are seeing different versions of the same work, which could lead to confusion. If this kind of functionality is needed, users can create a separate work. 

- (? License: You should not be able to change the license between versions. This would seriously complicate the issue of working out permissions and right. )

It may make sense to store these kinds of metadata at the work level rather than the version level.

**Comment by DanCoughlin** [comment]
Need more logic around what makes a version and what constitutes a new version.
