### ISSUE TITLE
Group membership is synchronized periodically with LDAP

### ISSUE THREAD

**Issue by rschenk** [psu-libraries/scholarsphere#32]
In current Scholarsphere we update a user's groups every 24 hours. We need to figure out how to do this in Scholarsphere v4. Ideally we would not require Scholarsphere to talk directly to LDAP, but instead possibly fetch this from the OAuth server. I don't know if this is technically possible and should investigate.

Update: consensus as of Oct 28, 2019 is that we'll just update a member's groups when they log in

**Comment by DanCoughlin** [comment]
related #37

**Comment by whereismyjetpack** [comment]
I believe this ticket to be closed.
