### ISSUE TITLE
What happens when OAuth login fails?

### ISSUE THREAD

**Issue by rschenk** [psu-libraries/scholarsphere#33]
This is a highly unlikely scenario, but currently the User model requires that the email be present and unique (case insensitive).

It is possible for either of these two validations to fail, if the OAuth server (which in this case is effectively a proxy for LDAP) either:
- returns a user's ldap record that contains no email address
- returns a user's ldap record where (1) the `access_id` field does not match the email address, (2) that email address already happens to exist in our User database.

If either of these scenarios are possible, we should decide what we're going to do about them.

**Comment by DanCoughlin** [comment]
Currently a 500 message, we should add logic to handle some oauth failure.
