### ISSUE TITLE
Tie Members into groups

### ISSUE THREAD

**Issue by DanCoughlin** [psu-libraries/scholarsphere#37]
We have groups, but no way of knowing what group a user is a member of. We can get this information from LDAP, via auth proxy.

## TODO

* create user_group_memberships join table to link users to their groups
* update the group membership of a user at login/session-renewal time
* update all additional LDAP information such as given and surname
* find or update by UID (ex. agw13)
* ~~distinguish between PSU-managed groups (i.e. umgs) and application-managed groups (i.e. "public" and "registered")~~ This can be done in #132

**Comment by awead** [comment]
After discussion at stand up today, the consensus at this point is to _not_ store groups in a table, but put them in the user table as a jsonb column. There would be an array of group names, updated by the auth proxy service when the user logs into Scholarsphere. This is how we've been doing in Scholarsphere 3, except there we use a semi-colon-delimited text field. Using jsonb enables us to have indexes on the group names for better performance.

## Todo

* add jsonb column to users table
* remove existing groups table and any associations
* modify auth proxy user registration process to update the user's groups

**Comment by rschenk** [comment]
@awead What specifically do we need to do for the fourth bullet point

> distinguish between PSU-managed groups (i.e. umgs) and application-managed groups (i.e. "public" and "registered")

Will individual users ever be a member of these groups? If so, what are the conditions? Will everybody always be a member of these two groups? Are these groups only used on the ACL side? We are not sure.

**Comment by awead** [comment]
@rschenk they're only used on the ACL side, but when determining access, a user's groups must be cross-referenced with a work's groups specified by its ACLs. A logged in user will always be a member of "public" and "registered", whereas a non-logged in, or guest users, would only be a member of "public."
