### ISSUE TITLE
Respond accordingly when a virus is uploaded

### ISSUE THREAD

**Issue by awead** [psu-libraries/scholarsphere#375]
If an infected file is uploaded to a work, how should we respond? Since the job should be run just prior to publishing the work, we should require that the virus check be complete before allowing a work to be published.

## WDLL

* require a complete virus scan for all files before allowing a work to be published (see notes)
* send some kind of notification when a virus is found (?)
* quarantine or delete infected files (?)
* periodically query files for their virus status

## Notes

If we require complete virus scans, this could impact user functions. If the metadata-listener service is not working, or Scholarsphere is unable to get updated virus reports, the user would not be able to publish their work. Files would be uploaded and metadata saved, but the work would remain in draft status.

**Comment by whereismyjetpack** [comment]
Apps and int will have a splunk alert that gets sent out for metadata listener fatal errors. 

My instinct is to maybe start small and IF a virus is found, give a warning? 

We also probably want an admin guide for updating a files virus status. I.e metadata listener finds a virus, but it's false positive. We should set the virus Boolean to false

**Comment by awead** [comment]
Good point. So, update metadata-listener to use `logger.warn` for viruses? We can ticket the admin actions.

**Comment by awead** [comment]
There's the log error here: https://github.com/psu-libraries/metadata-listener/blob/main/lib/metadata_listener/report/virus.rb#L29

I'm calling it done.
