### ISSUE TITLE
Display results of work downloads and views

### ISSUE THREAD

**Issue by awead** [psu-libraries/scholarsphere#382]
For simple display purposes, we should show the total downloads and views for works and files. Views should include a differentiation of views for the current version, versus views for all versions combined. File downloads can be displayed in the file view table.

**Comment by DanCoughlin** [comment]
For downloads we will have an aggregated graph for all downloads. If possible be great to have a column to know which file is being downloaded. 

We will need to update the JSON output that just has the view count and will need the file download count as well.

**Comment by srerickson** [comment]
closing this for #1210
