### ISSUE TITLE
Solr / Blacklight doesn't appear to be using the rails logger

### ISSUE THREAD

**Issue by whereismyjetpack** [psu-libraries/scholarsphere#435]
We have a custom formatter for our rails logs,and something within rsolr, or blacklight is not respecting this 

we are seeing messages like 
```
Solr query: get select {"qt"=>nil, "facet.field"=>["aasm_state_tesim", "work_type_ssim", "keyword_tesim", "resouce_type_tesim", "subject_tesim", "creators_sim"], "facet.query"=>[], "facet.pivot"=>[], "fq"=>["{!terms f=model_ssi}Work,Collection"], "hl.fl"=>[], "rows"=>10, "q"=>"test", "facet"=>true, "sort"=>"score desc, pub_date_si desc, title_si asc"}
```
which should perhaps be something like 
```
{"Solr query": "get select", "query":  {"qt"=>nil, "facet.field"=>["aasm_state_tesim", "work_type_ssim", "keyword_tesim", "resouce_type_tesim", "subject_tesim", "creators_sim"], "facet.query"=>[], "facet.pivot"=>[], "fq"=>["{!terms f=model_ssi}Work,Collection"], "hl.fl"=>[], "rows"=>10, "q"=>"test", "facet"=>true, "sort"=>"score desc, pub_date_si desc, title_si asc"}" }
```

It would be super rad if the hash that's being sent could be jsonified, so we could scour the logs more easily

**Comment by awead** [comment]
It's coming from here https://github.com/psu-stewardship/scholarsphere-4/blob/master/app/models/search_builder.rb#L26

This was intended only for local development, but I suppose changing it output json doesn't make it any less readable. Although, I don't envision `debug` being the log level for our production instance. Solr would also have this query information too. Might that be a better source to for log analysis?

**Comment by whereismyjetpack** [comment]
I have yet to look into a way to pattern match solr logs, but that's on my radar, I think if the logs were simply omitted that would suffice. 

It looks like `production.rb` is setting the log level to debug, If we want to ratchet that back, and leave the stanza in the search_builder i'd be ok with that too!

**Comment by awead** [comment]
This is `Blacklight.logger` and not anything we're doing locally.
