### ISSUE TITLE
badge for embargoed works in search results

### ISSUE THREAD

**Issue by srerickson** [psu-libraries/scholarsphere#441]
When listing works on the browse/search, we should indicate if a work is under embargo or withdrawn. In both cases the page for the work is public (the metadata is public) but associated files are not accessible. It would make sense to show this status as a "badge" that replaces the visibility badge (open access, psu-only).

**Comment by nicktiberi** [comment]
@srerickson - is this something we could take a stab at now, or should we wait for a designer to provide direction? If you feel OK with it, I'm happy to build this out. We'll just have to make a few decisions about colors and icons.

**Comment by srerickson** [comment]
@nicktiberi - yes, if you're comfortable taking this on, go for it. Ultimately, I'd like to redesign the entire "card" in which the title, author, etc. are displayed. But this would be a good first step.

Relates to #662

**Comment by srerickson** [comment]
Because the work states expressed by the badges aren't mutually exclusive, we will need to decide what state takes precedence when multiple state apply. Here is the order of precedence I'd prefer (states on the same line are mutually exclusive; the badge should use the first on the list that applies):

- Withdrawn
- Embargoed
- Penn State Only / Public

"Withdrawn" is complicated because it is a *work version* state, not a work state. (A work consists of a sequence of versions, each with a state of draft, published, or withdrawn). For the purpose of the badge, we'll need to infer a work-level state from the status of the work versions. Here's what I have in mind:

- A work is considered "Withdrawn" if it has at least one withdrawn work version and no published work versions

This is beyond the scope of this issue, but I'd like to eventually handle the "draft" status similarly:

- A work is considered "Draft" if it only has one version and it is in draft state.

We may to run into problems here because of differences between the dashoard and search pages – @awead should weigh-in on this because I always have trouble wrapping my head around this part of the application.

For icons:

- "Embargoed" can use the "lock clock"  icon
- "Withdrawn" can use the "hide source" icon

**Comment by awead** [comment]
In the public search, each result will be the equivalent of the latest published version of a work. We don't show any draft versions, previously published versions, or withdrawn versions. The dashboard will show the latest _version_ of the work no matter what its state is. However, it only shows those work versions that the user has edit access to.

So I think the logic should be the same whether you're in the dashboard or not.

**Comment by srerickson** [comment]
As mentioned at standup, this issue is now focused on the embargoed badge. We'll handle the "withdrawn" status in another issue (#1010).

**Comment by nicktiberi** [comment]
@srerickson - it appears that embargoed works are excluded from search results unless the user is an admin:

https://github.com/psu-libraries/scholarsphere/blob/248f6e3e43f794e1c400c6d5e4ca836f674e2c32/app/models/search_builder.rb#L29-L34

Given that, and the fact that the request for this ticket is that the embargoed badge shows in the search results, do we still want to add this badge? It seems it would only be seen by ScholarSphere admins.

**Comment by srerickson** [comment]
@nicktiberi does that logic apply to both search and dashboard? I can see why excluding embargoed works from search makes sense, but not the dashboard.

**Comment by awead** [comment]
Embargoed works are not returned in the public search. However, in `Dashboard::SearchBuilder` they are, so the embargoed badge would only apply in an admin public search or a user's dashboard search.
