### ISSUE TITLE
Revist blue bar placement

### ISSUE THREAD

**Issue by awead** [psu-libraries/scholarsphere#489]
We need a consistent pattern regarding placement of blue bar. It seems it's contextual for the user most of the time, but at other times not. Ex. homepage vs. dashboard. The blue bar could be contextual to the page.

**Comment by srerickson** [comment]
I feel like we may have sorted this out, magically. The blue bar is often a page title, except on resource pages where it provides some work or collection-level navigation: version nav, work settings, edit version, etc.

Seems to me we can close this.

**Comment by srerickson** [comment]
@awead , I'm not sure I understand this issue and I'm inclined to close it.
