### ISSUE TITLE
Merge repositories

### ISSUE THREAD

**Issue by DanCoughlin** [psu-libraries/scholarsphere#5]
We have two repos and working that work into our new repo scholarsphere-4

**Comment by rschenk** [comment]
The database/model layer is completely ported over as of today. We've not ported over the workflow UI yet. I'm not sure if we _want_ to bring that over verbatim, or do a round of wireframing and UI design first?

**Comment by DanCoughlin** [comment]
Going to move the workflow UI over. It may end up being reworked but this will give us something to test.
