### ISSUE TITLE
download reports needs discussion

### ISSUE THREAD

**Issue by DanCoughlin** [psu-libraries/scholarsphere#504]
When the dean has someone upload files, she gets a report that should include those files uploaded on her behalf, but she only gets information related to files she has uploaded. 

From Discussion with Adam:
In both versions (3 and 4), the depositor is a creator. However, in some cases, like a proxy deposit situation, the depositor isn't the creator, so we have to keep the two separate, but also be able to link them.

I think SS4 will be able to draw clearer distinctions between the differences. For one, we're making the data a little more rigorous. In SS3, the only connection between depositor and creator is that the names or PSU ids match. It's not exactly solid. In SS4, there will be "actors" who are the creators of the content and when that person is also the same person that logged in and uploaded the content, then all those database records will be linked together.

That could change the way we report the statistics and we could count downloads for each "actor" that has a file in Scholarsphere.

The depositor is really a intra-application concept. It's the person who logged in and uploaded the file. The creator is the public metadata. 95% of the time, they are the same person, but for those 5% edge cases, we have this distinction in terms.

**Comment by srerickson** [comment]
closing this; see #1210
