### ISSUE TITLE
Don't use the "migration" destination for the 4.0 production release

### ISSUE THREAD

**Issue by awead** [psu-libraries/scholarsphere#639]
Currently, Scholarsphere 3.11 (production) will be migrating to https://scholarsphere-migration.dsrd.libraries.psu.edu and it's associated S3 bucket name. These should change to something with a "prod" or "production" designation.

## WDLL

* Update Scholarsphere 3.11 SS4-client configuration to point to appropriate S3 bucket (`edu.psu.libraries.scholarsphere.prod` ?)
* create new https://scholarsphere-prod.dsrd.libraries.psu.edu location
* ensure S3 configuration matches SS4-client configuration

**Comment by whereismyjetpack** [comment]
The production release will live at https://scholarsphere.psu.edu, with a vanity domain of https://scholarsphere.k8s.librarie.psu.edu. the bucket will be `edu.psu.libraries.scholarsphere.prod` (it's already been created) we'll generate temporary credentials for the client to use.

**Comment by awead** [comment]
@whereismyjetpack there's already content in that bucket now. Do you know what that's from? The credentials will need to be used by the SS3 server for multiple migrations. This doesn't read as "temporary" to me. Is that an issue?
