### ISSUE TITLE
Public message for Penn State works

### ISSUE THREAD

**Issue by awead** [psu-libraries/scholarsphere#662]
Display an information message to the user, similar to the embargo message, if a public user access a Penn State work. It should let them know they don't have access to the files.

## WDLL

On a resource page that has 'Penn State Only' access settings, a message should appear to unauthenticated users:

> Files are only accessible to users logged-in with a Penn State Access ID.

**Comment by srerickson** [comment]
@nicktiberi, you might take a look at this one.

**Comment by nicktiberi** [comment]
@srerickson - my current approach is to combine the various file access scenarios into a single message, which varies based on the access state of the work/work version.

If you're OK with this approach, please let me know if any of the states below should be combined into a single state, and what the messaging should be for each state. Thanks!

### Scenarios
- withdrawn
   - heading: "Withdrawn"
   - public_message: "This version of the work has been withdrawn. Its files are no longer accessible."
   - edit_message: "You have permission to access the files as an editor of the resource."
- embargoed
   - heading: "Embargoed until %{date}"
   - public_message: "Files are not accessible during the embargo."
   - edit_message:  "You have permission to access the files as an editor of the resource."
- Penn State only / public
   - heading: "Penn State Only"
   - public_message: "Files are only accessible to users logged-in with a Penn State Access ID."
   - edit_message:  "You have permission to access the files as an editor of the resource."
- withdrawn + embargoed + Penn State only
  - *same as withdrawn* 
- withdrawn + embargoed
  - *same as withdrawn*
- withdrawn + Penn State only
  - *same as withdrawn*
- embargoed + Penn State only
   - heading:  "Embargoed until %{date}"
   - public_message: "Files are not accessible during the embargo. After the embargo period, files will be accessible to users logged-in with a Penn State Access ID. "
   - edit_message:  "You have permission to access the files as an editor of the resource."
