### ISSUE TITLE
Investigate better spam filters for contact form

### ISSUE THREAD

**Issue by awead** [psu-libraries/scholarsphere#669]
Spam is coming in directly to the ssphere-support@psu.edu. Maybe we can stop that?

**Comment by srerickson** [comment]
this can be move to 4.01 I think

**Comment by whereismyjetpack** [comment]
I did some digging, and spam is also coming through the contact form. robots are bypassing the recaptcha, maybe newer versions are better? maybe we can see how bad 4.0 is?

**Comment by awead** [comment]
We need to change the email. It's not a filtering issue.
