### ISSUE TITLE
Redirects to logins are returning 500 

### ISSUE THREAD

**Issue by awead** [psu-libraries/scholarsphere#704]
From a "clean" Firefox session, if I visit `/dashboard`, I get **Server Error**. Looking at DataDog, I'm seeing:

`URI::GID::MissingModelIdError: Unable to create a Global ID for User without a model id.`

This is also reproducible locally. It also may be tangentially related to #692. Devise wants to _redirect_ to a login page, but that may ultimately have to be a POST method, which you can't do according to the HTTP spec. We may ultimately have to do something like redirect to the home page and have the user click on the login link.

**Comment by whereismyjetpack** [comment]
I think a redirec_to with a flash message that say something like 'you need to be logged in to see this page' would suffice. ?

**Comment by awead** [comment]
Yes, that's the Devise default, which is what we may just go with....

**Comment by awead** [comment]
The related PR fixes the problem, and now going to `/dashboard` will redirect to the azure login. But, we'll see what comes of the other POST issue.
