### ISSUE TITLE
Include File MD5 with Other File Info

### ISSUE THREAD

**Issue by srerickson** [psu-libraries/scholarsphere#708]
It's important for users and curators to be able to confirm that the deposited file is the same as the file they have. The md5 checksum should be accessible through the UI. I think we can just add it along with other per-file info (size, content type, date)

UI Note:
- this could look like github commit hashes, show the abbreviated checksum: `md5: c9f4de...`
- mousing over the checksum shows the full value
- clicking copies to clipboard

**Comment by srerickson** [comment]
__Update 1/31/22__: Please ignore the comment below. I'm leaving it for posterity, but this issue does not require using S3 Etags. We should probably be getting checksums through our general file characterization workflow. 

To clarify: the point of this is to be able verify the integrity of the data "at rest" on S3. The displayed checksum should not be based on Fits since that involves transferring the data. I think our best (and only) option is to use S3s Etag (which is not md5 in every case, but will be in ours).

**Comment by awead** [comment]
For multipart uploads, which is everything that's coming in from the UI, the checksum won't be the md5.

See https://teppen.io/2018/06/23/aws_s3_etags/

Unfortunately, the above Python code sample doesn't match the etags we're getting from S3. We could delve into this further, but we may not be able to find a reliable, consistent way to re-calculate the non-md5 etags. If the chunk size chagnes, for whatever reason, the etags would be different for those files than for the others.
