### ISSUE TITLE
500 Error for draft work resources

### ISSUE THREAD

**Issue by awead** [psu-libraries/scholarsphere#717]
When requesting the uuid for a _Work_ that is still in draft, i.e. it has only one version and that version is in draft status, we're getting a 500 error:

ActionView::Template::Error: undefined local variable or method `model_name' for #<NullWorkVersion:0x00007fc0943c84d8>

Similar to #714

**Comment by rschenk** [comment]
@awead @srerickson We need to decide what the desired behavior is. When a user hits a resource page for a `Work` that is not yet published, what should happen?

**Comment by srerickson** [comment]
My preference is 404.

**Comment by awead** [comment]
@srerickson Even if they're an admin? They'd still be able to view the work version page, via the dashboard.

**Comment by srerickson** [comment]
Yes, let's do 404 for all cases.
