### ISSUE TITLE
Meta Description, Link Descriptive Text

### ISSUE THREAD

**Issue by whereismyjetpack** [psu-libraries/scholarsphere#720]
I was running lighthouse against ScholarSphere, and it flagged 2 issues that seem pretty quick to fix. 

1.) Document does not have meta description
https://web.dev/meta-description/?utm_source=lighthouse&utm_medium=devtools

2.) "read more" /about link does not have descriptive text
https://web.dev/link-text/?utm_source=lighthouse&utm_medium=devtools

## WDLL 

Add description meta tags to the home page.

**Comment by awead** [comment]
Is this just for the home page? We have the meta property "og:description" for works and collections, but this seems like a more general-level description. I think we need to answer:

1) Does every public page need some meta tags, such as "description"
2) If so, is the basic "description" property sufficient?

The link descriptions sound a little more dubious. I agree that "read more" isn't the best, but maybe there's a better way with some microdata (i.e. schema.org) or alt text.

**Comment by whereismyjetpack** [comment]
This was _just_ for the home page, and this is not an area i'm even the slightest bit a professional in, but the SEO score was pretty low because of those two items (82/100)

**Comment by srerickson** [comment]
based on the comment above, it seems like the homepage is our main concern and the basic description meta tag is sufficient. The meta tag can be set to the text in the `home.intro.content` setting. Actually, it may be better to just define this text under `description` and update the home page view to use that setting. Your call.

**Comment by nicktiberi** [comment]
@srerickson - for the "read more" link, what would you like to change it to? I was thinking something like **About ScholarSphere** or **Read More About Scholarsphere**.

<img width="697" alt="Screen Shot 2021-05-18 at 9 37 43 AM" src="https://user-images.githubusercontent.com/639920/118661235-ee056e00-b7bc-11eb-94a5-64324d498760.png">

**Comment by srerickson** [comment]
@nicktiberi - let's go with "Read more about ScholarSphere" (with period outside link tag).

![image](https://user-images.githubusercontent.com/876323/118670623-c4504500-b7c4-11eb-87a8-c2f5863785fd.png)
