### ISSUE TITLE
Better Styling for Markdown Pages

### ISSUE THREAD

**Issue by srerickson** [psu-libraries/scholarsphere#736]
The css for markdown pages like the "about", "help", and policy pages could be improved.

- Spacing between nested header (e.g. h2/h3) tags doesn't look great by default
- The content area should be narrower instead of taking up the entire width of the window.

**Comment by nicktiberi** [comment]
@srerickson - looks like you already took care of item 2 in the ticket via this commit: https://github.com/psu-libraries/scholarsphere/commit/0687e2646eabf71d5bc877320e4c2c99f057d5f6#diff-e08b9b1dd7ea3e83e27061025d8067bb05b0edf4f63ba7edac08eb7265d871c7

The content area is no longer taking up the full width of the screen.

Would you mind elaborating a bit regarding the issues with the spacing between nested header tags? It looks OK to me, but happy to adjust as needed.

**Comment by srerickson** [comment]
@nicktiberi , let's hold on this until some of the new documentation pages are done (eg., #793).

**Comment by srerickson** [comment]
closing in favor of #1152
