### ISSUE TITLE
Typo in Downloads Report

### ISSUE THREAD

**Issue by DanCoughlin** [psu-libraries/scholarsphere#749]
The monthly ScholarSphere report refers to 'Product Name' instead of ScholarSphere:

Dear Daniel Coughlin, 
You had 1 new downloads last month across your 21 files in ScholarSphere.

Interested in sharing, archiving, and preserving other work? Consider depositing any of the following in **Product Name**

**Comment by srerickson** [comment]
Is there any chance we could do a patch release fixing this before the mail goes out again next week?
(I can work on it)
