### ISSUE TITLE
Inconsistency between search results and dashboard

### ISSUE THREAD

**Issue by srerickson** [psu-libraries/scholarsphere#751]
As admin, works that appears as “v1 published” on main search page can appear as “v1 draft” on the dashboard. It seems the dashboard reflects state from before works were published. May be an indexing issue.

Here is an example.

dashboard: https://scholarsphere.psu.edu/dashboard?search_field=all_fields&q=%22objective+assessment+metrics%22
search: https://scholarsphere.psu.edu/catalog?search_field=all_fields&q=%22objective+assessment+metrics%22

(appears as draft in first but published in second)

**Comment by srerickson** [comment]
may be related to #651

**Comment by awead** [comment]
It's possible this is a race condition between the Files step and the Review & Publish step. What would happen is, the user uploads the files and clicks Save and Continue. Some background jobs kickoff and the user continues on to Review and Publish. They do that step relatively quickly, and the work is published and indexed in Solr. However, the background job from the Files step is still processing and it has the out-of-date metadata attached to it (possibly) so when it finishes, it also reindexes (possibly) and that's what overwrites the solr record.

Solutions would be:
* implement the fix in #651 and don't reindex during any of the interim steps in the form
* look into the Shrine-related background jobs and ensure they aren't indexing anything in Solr.
