### ISSUE TITLE
Work title doesn't appear on Work Settings Page

### ISSUE THREAD

**Issue by srerickson** [psu-libraries/scholarsphere#754]
For a work without a published version, the title doesn't appear on the Work Settings page as expected.

```rb
# in the work settings view:
(@work.latest_published_version || @work.latest_version).title
```
When there is no published version, this resolves to the nil title of a `NullWorkVersion`, not the actual title of `@work.latest_version`

For example: https://scholarsphere.psu.edu/dashboard/works/9778/edit

**Comment by awead** [comment]
@srerickson what should the title be? "Unpublished work" or something similar?

**Comment by srerickson** [comment]
I think it should just be `@work.latest_version.title` in all cases --- i.e., use the title even if the version isn't published. I *think* that's safe.

**Comment by awead** [comment]
Oh right, because you can't even save a draft version without a title 👍
