### ISSUE TITLE
Error  when entering a non-psu contributor ORCID

### ISSUE THREAD

**Issue by bdezray** [psu-libraries/scholarsphere#755]
The ORCID number of a non-psu contributor (never affiliated with PSU)  is not being accepted by ScholarSphere even though it is this individual's correct ID. 
<img width="526" alt="ORCID issue - Sharma" src="https://user-images.githubusercontent.com/44412949/101027946-9d6bc280-3546-11eb-859e-1d9f6f1aab47.png">

**Comment by srerickson** [comment]
@bdezray, @awead, did we confirm that this was because the user did, in fact, already exist? Can this be closed?
