### ISSUE TITLE
Work / WorkVersion Link Confusion

### ISSUE THREAD

**Issue by srerickson** [psu-libraries/scholarsphere#765]
Some users are stumbling into a problem where they are using and circulating links to a _work version_ when they mean to be using links to _the work_. One reason this happens is that the links used on the dashboard are version links but the links on the search page are work links.

I'd like to make it harder for people to accidentally use version links when they probably want a work link. To that end, can we make the links used on the dashboard work level links?

**Comment by awead** [comment]
## WDLL
* ~~when on the dashboard and the work version is published, send the user to the work uuid and _not_ the work version uuid~~
* this should resolve itself automatically once #1026 is closed, since the proposal there is that all search results are works
