### ISSUE TITLE
Collections ordering inconsistency

### ISSUE THREAD

**Issue by srerickson** [psu-libraries/scholarsphere#790]
While working on this [this collection](https://scholarsphere.psu.edu/resources/48e7319c-0321-4094-85ed-cbf83ea1a062) I noticed a problem with collection work ordering: I added a work to the collection (the readme) and set it to be the first item in the collection; that worked, but I noticed that when I go back to the collection edit form, the order is not the same (readme is no longer first).

**Comment by rschenk** [comment]
I've duplicated this, working on the fix. Shouldn't be too bad.
