### ISSUE TITLE
Help choosing a license

### ISSUE THREAD

**Issue by srerickson** [psu-libraries/scholarsphere#793]
Add documentation or a guide to help depositors select an appropriate license.

**Comment by srerickson** [comment]
Current license options are defined here: [licenses.yml](https://github.com/psu-stewardship/scholarsphere/blob/develop/config/authorities/licenses.yml). We will need descriptions for for each "active" license option.

The old license descriptions:

Creative Commons licenses can take the following combinations, which is what a depositor sees on the page where metadata (descriptions) are entered. Via the drop-down menu, the depositor may select any of the following licenses (these are all described at "Licensing Types" on the Creative Commons site):

## Attribution 4.0: CC BY

With this license you allow others to "distribute, remix, tweak, and build" on your deposited content - including for commercial purposes - provided they attribute you as the original creator.

## Attribution-Share-Alike 4.0: CC BY-SA 

With this license you allow others to "remix, tweak, and build" on your deposited content, including for commercial uses, provided they attribute you as the original creator AND incorporate the same level of licensing (i.e., CC BY-SA) for the newly resulting creation. "All new works based on yours will carry the same license, so any derivatives will also allow commercial use."

## Attribution-NoDerivs 4.0: CC BY-ND 

With this license you permit "redistribution, commercial and non-commercial," provided the content remains unaltered and intact (i.e., whole) and provided you are attributed as the original creator.

## Attribution-Non-Commercial 4.0: CC BY-NC

With this license you allow others to "remix, tweak, and build" on your content in non-commercial ways. While they must credit you as the original creator and while the remixed, tweaked, or expanded upon content must remain non-commercial, they do not have to apply identical license terms on the new content.

## Attribution-NonCommercial-NoDerivs 4.0 CC BY-NC-ND

With this license you share your work with others and allow them to download your work, provided they attribute you as the creator and refrain from changing the content in any way and from using it for commercial means.

## Attribution-Non-Commercial-Share-Alike 4.0: CC BY-NC-SA

With this license you allow others to "remix, tweak, and build" on your content in non-commercial ways, provided they give you credit (as the original creator) and also apply the same license level to the newly resulting creations.

## Attribution-Non-Commercial-Share-Alike-NoDerivs 4.0: CC BY-NC-SA-ND

With this license you share your work with others and allow them to download it, provided they attribute you as the creator; they must also refrain from changing the content in any way and from using it for commercial means.

## Public Domain Mark 1.0 

When content is in the public domain, it has no known copyright owner.

## CC0 1.0 Universal 

With this license you are waiving your rights as copyright owner to the content you upload. This means your content may be distributed and reused without attribution, without restriction. CC0 is a license that one applies to one's own work; rarely does one apply it to another's work, unless one has the appropriate rights to do so.

## All rights reserved

With this license you - as the copyright holder - reserve all rights held under copyright law, such as for distribution and creation of derivative works. This means that no one can use your content in a work - such as a presentation or article - or create derivatives from it without your permission.

**Comment by srerickson** [comment]
Ways to group these options & structure documentation, flow:

__Is this work under copyright in the US__? This guide is [helpful](https://guides.lib.umich.edu/copyrightbasics/copyrightability).

- If not, choose [No Copyright US](https://rightsstatements.org/page/NoC-US/1.0/?language=en).
  - This option is often appropriate for data that is not copyrightable in the US.
  - (Note, Ana recommends removing the public domain mark option)
- If it is under copyright, which is most often the case, then you may apply a license as the copyright holder:
  - To apply a license, choose from:
    - Licenses for creative works and documents (CC options). We can refer to this [guide](https://copyright.psu.edu/copyright-basics/creative-commons/). 
    - Licenses specifically for software
  - You may also choose not to apply a license (this is the legal default), in which case choose "[In copyright](https://rightsstatements.org/page/InC/1.0/?language=en)"

Note: It's important for depositors not librarians to make these choices. We shouldn't be giving depositors legal advice (e.g., we can't tell folks the status of their code wrt Penn State's IP policy).

**Comment by anaelizabethenriquez** [comment]
Suggestion for drop-down, if possible:


Rights Statements
	No Copyright - United States (Public Domain)
	In Copyright (All Rights Reserved)

Creative Commons Licenses (for copyrighted material other than software)
	Attribution 4.0 International (CC BY 4.0)
	Attribution-ShareAlike 4.0 International (CC BY-SA 4.0)
	Attribution-NonCommercial 4.0 International (CC BY-NC 4.0)
	Attribution-NoDerivatives 4.0 International (CC BY-ND 4.0)
	Attribution-NonCommercial-NoDerivatives 4.0 International (CC BY-NC-ND 4.0)
	Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0)
	Public Domain Dedication (CC0 1.0)

Software Licenses (for copyrighted software)
	Apache 2.0
	GNU General Public License (GPLv3)
	MIT License
	BSD 3-Clause License

**Comment by nicktiberi** [comment]
@srerickson - we now have a link to the docs under the license dropdown. Is this issue still relevant?
