### ISSUE TITLE
Unable to add editors (in work settings) to draft work

### ISSUE THREAD

**Issue by bdezray** [psu-libraries/scholarsphere#795]
The ability to add editors to a draft work does not appear to be functioning. The following error appears when attempting to update editors. 
![Screen Shot 2021-01-04 at 7 03 16 AM](https://user-images.githubusercontent.com/44412949/103533436-19656d00-4e5b-11eb-95d3-f6b40115e489.png)

**Comment by whereismyjetpack** [comment]
@bdezray The ability to edit a user from a draft work appears to be working for me. This does, however, appear to be an issue with urlencoding, or perhaps bad user input. 

> "error: URI::InvalidURIError: bad URI(is not URI?): "/search-service/resources/people/userid/Heather Hines"

Perhaps try putting in the users access id? I think that's what that form expects. we should validate that before displaying an error like this to the user.

Splunk Query: ( good for 7 days)
https://splunk.ois.psu.edu/en-US/app/search/search?sid=1609772208.159775_2857FFD7-2774-4137-A7E5-8D056B663985

**Comment by bdezray** [comment]
hmmm here is the error I get when I try putting in the users access id.
![Screen Shot 2021-01-04 at 9 59 39 AM](https://user-images.githubusercontent.com/44412949/103548372-b502d780-4e73-11eb-8533-df6fbb15e813.png)

**Comment by whereismyjetpack** [comment]
did we try just `hmh19`?

**Comment by bdezray** [comment]
That works!! Maybe for now we can add a note to the help text specifying that format? It would be great to have this bar work with the same functionality as the creator ones where you can search for the user in the future as well as have a place where it lists people with current edit access once granted.

**Comment by whereismyjetpack** [comment]
Excellent!! I think we could create a ticket to update the messaging / validations on this form to prevent this from happening in the future.

**Comment by srerickson** [comment]
@awead , 
For the validation: "User [name] could not be found."
For the help text: "Requires user's Penn State Access ID (e.g., xyz500)"

thanks!
