### ISSUE TITLE
Return 404 for unknown facet fields

### ISSUE THREAD

**Issue by awead** [psu-libraries/scholarsphere#806]
# Bug Report

## Description

Probably due to some old search urls that are still out there, a query for a facet field that doesn't existing anymore will cause `ActionView::Template::Error: undefined method 'facet_config' for nil:NilClass`

We should return 404 for these.

## To Reproduce
1. Create a link such as `/catalog?f%5Bbased_near_sim%5D%5B%5D&f%5Bresource_type_sim%5D%5B%5D&sort`

**Comment by rschenk** [comment]
@srerickson This does not actually raise the error that Adam describes—perhaps this was fixed previously, or perhaps we installed an update to blacklight. Either way, the [example url](https://scholarsphere.psu.edu/catalog?f%5Bbased_near_sim%5D%5B%5D&f%5Bresource_type_sim%5D%5B%5D&sort) does not bomb out, it simply renders a list of search results with no facets selected, which in my humble opinion is probably a better solution than 404ing
