### ISSUE TITLE
Admin ability to add authors without ORCID (or PSU ID)

### ISSUE THREAD

**Issue by srerickson** [psu-libraries/scholarsphere#808]
# Feature Request

Admins should be able to create new authors and add them to a work without setting an ORCID.

## Describe the solution you'd like

The ORCID validation on the "New Creator" form should not apply to Admins

## What does "done" look like?

On the "New Creators" form, when an admin clicks save without entering an ORCID, the author should be saved.

**Comment by awead** [comment]
This should be easy to implement. The restriction on ORCIDs is UI-only, so it should be a matter of checking the user's admin status and allowing the form to save the new ORCID-less creator if they have enabled their admin rights in the their profile.

**Comment by srerickson** [comment]
I'd like to think about and discuss this a bit more, so please hold on implementing.

**Comment by srerickson** [comment]
closing this in favor of #814
