### ISSUE TITLE
Author order reversed when you create a new version.

### ISSUE THREAD

**Issue by srerickson** [psu-libraries/scholarsphere#809]
The order of authors is reversed when you create a new version.

Example: https://scholarsphere-qa.dsrd.libraries.psu.edu/resources/8c7866cd-8dfd-44c4-a0f8-385218b63173

# Steps to reproduce

- create a new work with a bunch of authors and publish it.
- create a second version (just draft is fine) and look at the contributors form: the order is reversed.

**Comment by srerickson** [comment]
If possible, it would be great to release a patch release with this bug fix.

**Comment by awead** [comment]
This has been added to the current sprint and we can release it after retro next week.

**Comment by rschenk** [comment]
My suspicion from standup was correct, and this is a super easy fix
