### ISSUE TITLE
Update UI to reflect new requirements when adding creators

### ISSUE THREAD

**Issue by awead** [psu-libraries/scholarsphere#821]
Because we can now add creators without identifiers, the UI needs to change a bit.

## WDLL

* Orcid is not longer required in new creator form
* require _both_ first and last name (?)
* require email (?)
* adding unidentified creators inserts new record into Author table without a linked Actor record
* entering an Orcid ID will populate the other fields with the resulting metadata

**Comment by srerickson** [comment]
I don't think we should require first names because we can expect some non-person authors. (A corolary is that the last name field may include non-person names). Additionally, I don't think we should require emails.
