### ISSUE TITLE
Draft changes are visible to the public

### ISSUE THREAD

**Issue by awead** [psu-libraries/scholarsphere#823]
# Bug Report

## Description

When a draft version of a published work exists, users will be able to see the changes in the draft in the work history.

## To Reproduce

TBA

## Expected behavior

Work history changes for draft versions should only be visible to users who have edit permissions on the work.

**Comment by awead** [comment]
Duplicated of #856

**Comment by rschenk** [comment]
This was erroneously closed, but it's still an issue
