### ISSUE TITLE
Terms of use page

### ISSUE THREAD

**Issue by srerickson** [psu-libraries/scholarsphere#826]
The terms of use page never made it over to ss4.0:

https://scholarsphere-3.libraries.psu.edu/terms

**Comment by anaelizabethenriquez** [comment]
I'd be inclined to post these terms on the new site without major changes. 

Minor changes suggested:

- Fix this typo/encoding issue: "(see 17 U.S.C. Â§512(c)(3)." should be (see 17 U.S.C. § 512(c)(3)."
- Modify some language that's no longer in use (e.g. "access level," right?)
