### ISSUE TITLE
Version Endpoint

### ISSUE THREAD

**Issue by whereismyjetpack** [psu-libraries/scholarsphere#828]
# Feature Request
A route/api/or healthcheck that displays version information
## Describe the solution you'd like
A way to tell from the application what version it thinks it is
## Any alternatives you've considered?
i have not.
## What does "done" look like?
a request to an endpoint can display version information to the user. 
How will we know when we've successfully implemented this?

I haven't thought too much about what this might look like, does it return json, html, do we have both formats etc. Opening this up as a way to start the discussion. 

Presently the deployments get injected into them an `APP_VERSION` environment variable, and this matches up with the image tag, (git commit sha, or version tag)

**Comment by awead** [comment]
The easiest would be a health check. That seems to be the least invasive. API would be good to, and perhaps more formal, since it could be included as part of the spec, but currently all API requests require authentication, and it'd be nice to offer this without that.

Also, why not both?

**Comment by whereismyjetpack** [comment]
I think starting with a healthcheck makes sense, all the machinery is already there, and adding to it should be trivial. 

I can start by just pulling APP_VERSION and we an evolve it over time?
