### ISSUE TITLE
Deployments for preview branches

### ISSUE THREAD

**Issue by awead** [psu-libraries/scholarsphere#831]
It looks like when we have a preview branch, which are deployed, there's a corresponding deployment entry in Github:

https://github.com/psu-stewardship/scholarsphere/deployments/activity_log?environment=version-health

If this intentional, will they be deleted once the branch is removed? Another option would be ignore preview branches and not give them "environment" entries, but I don't know what the intention is here.

**Comment by whereismyjetpack** [comment]
We can certainly ignore preview branches, and leave deployments in gh opt in.

**Comment by awead** [comment]
I'm not sure if we should ignore them (yet). I think my main concern would be that they go away when they're supposed to. Having a ton of "aborted" badges, or whatever the flag is, could start looking odd. It is a nice way to communicate to us that our deployment is ready....

**Comment by whereismyjetpack** [comment]
That was my thought. there is a way to communicate to the API that an env is ephemeral; which we are doing. If they don't clean up after themselves maybe we can have a finalizer do it.

I'll use the version_check PR as a guide for what to do?

**Comment by awead** [comment]
Sounds good. I just merged the pr, which deleted the preview branch, but the deployment is still there.
