### ISSUE TITLE
Rescue Mailer errors that aren't recoverable 

### ISSUE THREAD

**Issue by whereismyjetpack** [psu-libraries/scholarsphere#843]
# Bug Report

## Description
The monthly email job will retry sending to an unknown user, and then eventually end up in the deadset queue. we should perhaps rescue these errros

## To Reproduce
```
Net::SMTPFatalError: 550 5.1.1 <id@psu.edu>... User UNknown
```

**Comment by srerickson** [comment]
look at how RMD handles this.
