### ISSUE TITLE
Contact form should use LibAnswerws not ServiceNow

### ISSUE THREAD

**Issue by srerickson** [psu-libraries/scholarsphere#846]
# Feature Request

The ScholarSphere contact form should be backed by LibAnswers not the IT ticketing systems (ServiceNow).

## Describe the solution you'd like

When a user fills out the "contact us" form, the question should be created in the LibAnswers systems where the libraries manages other public-facing service and reference questions.

## Any alternatives you've considered?

It could be created in both (a nightmare)

**Comment by awead** [comment]
@srerickson Are there any other existing applications in the Libraries (or elsewhere) that are integrating with LibAnswers in this way? We'd need to know if this is feasible at all. They have an API, but I don't see anything that directly matches this use case.

**Comment by srerickson** [comment]
One possibility is that the "Contact Us" link would redirect to a form like this:
https://libraries.psu.edu/research-consultation-request

(hosted on main Libraries site)

**Comment by awead** [comment]
We could go the "Ask a Librarian" route that is used in the catalog. This is using libanswers, and has a link that directs you to the page above.

See https://catalog.libraries.psu.edu/

**Comment by srerickson** [comment]
There are two possibilities and I'm not sure which will be better for the purposes of limiting spam. 

1. Use the existing "incident" form but send submissions to the email address associated with our new LibAnswers queue. The nice thing about this approach is we can continue to use the CAPTCHA.
2. Replace the existing form with the embedded html/js from LibAnswers. This is nice because it makes it easy to customize the form the LibAnswers UI. There is no CAPTCHA, however. 

@awead  -- thoughts?

**Comment by awead** [comment]
Option 1 gives us more control, but requires maybe more work. Option 2 seems easier? If I understand it, we can just drop in the LibAnswers code. I don't think CAPTCHA is crucial. If we use a new email address (and don't publish it) that should cut out the spam significantly. I'd lean towards the doing-it-the-way-everyone-else-is/simple way, and if that doesn't work, try something more complicated.

**Comment by awead** [comment]
We can choose option 1, and use the existing form (no extra work) and provide a new email address that will link up to LibAnswers. @whereismyjetpack is working on getting a new email.

**Comment by awead** [comment]
## TODO

Change email to `contact@scholarsphere.psu.edu` ✈️ 

This is so we can send outgoing email from the address. `psu.edu` has different policies that make this difficult. Using our own vanity domain makes this easier.

**Comment by whereismyjetpack** [comment]
I've updated my ticket with EIT to ask for these changes.
