### ISSUE TITLE
Clear out Search History

### ISSUE THREAD

**Issue by whereismyjetpack** [psu-libraries/scholarsphere#857]
# Bug Report

## Description
Presently we aren't managing search history, and the searches table grows. 

## Expected behavior
A way to elminate, or clear old search history

## Screenshots
```
 public | searches                    | table | postgres | 447 MB     |
 ```

Related issue
https://github.com/projectblacklight/blacklight/issues/1652

Cronjob seems to be a common pattern. if we had a rake task, we could use a kubernetes cronjob to clear it on a schedule. More desirable would be to turn off the functionality as it doesn't seem we ever use it.

**Comment by awead** [comment]
`Blacklight::SearchContext` is the included module into `CatalogController` where this is all happening. We could theoretically exclude the entire module, and then we wouldn't be capturing any search history at all.

**Comment by whereismyjetpack** [comment]
I'm curious what else that does. If we never need a logged in users search, seems like a decent approach.

**Comment by awead** [comment]
There's a feature in Blacklight where you can save your search history. Although, this is still technically "running," we don't link to the page where users can view and save their searches, so turning this off wouldn't cost us anything, as far as I can tell.
