### ISSUE TITLE
Retrieve a list of DOIs

### ISSUE THREAD

**Issue by awead** [psu-libraries/scholarsphere#859]
# Feature Request

We need to check all our DOIs to make sure they resolve correctly. In order to do that, we need to get a list of all our existing ones. The API has a method for that: https://support.datacite.org/docs/api-get-lists

## Describe the solution you'd like

Add `get_lists` option to our DataCite::Client. It will need to support paginating through all the results.

## What does "done" look like?

This is a rough idea:

    > client = DataCite::Client.new
    > results = client.get_list
    > results.dois
    => [Enumerable]
    > results.next_page?
    => true
    > results.next_page
    > results.dois
    => [Enumerable]
    > results.next_page?
    => false

We could also take a more functional approach and return new results objects for each page instead of mutating it each time.

How will we know when we've successfully implemented this?

When we can loop through an entire list of all our DOIs and extract out the id, perform a GET request on the resulting url and see if it resolves.

**Comment by srerickson** [comment]
I don't think we need this as a feature since we can get the DOIs directly through Datacite this way:

```
curl https://api.datacite.org/dois\?client-id\=psu.scholar\&page\[size\]\=500 | jq -r '.data[].attributes | [.doi, .url] | @csv'
```

**Comment by awead** [comment]
Fair enough. However, this isn't automated. We might want to consider having a scheduled check of all DOIs. This could guard against public DOIs becoming unintentionally blocked. Although, I'm not sure how that could happen, it's always nice to know we're checking.
