### ISSUE TITLE
Cancel button prevents works from showing up on the dashboard.

### ISSUE THREAD

**Issue by srerickson** [psu-libraries/scholarsphere#860]
# Bug Report

## Description
Clicking the "cancel" button during initial deposit (creating fist version of a work) causes the work to not show up in the dashboard even when the work version exists in draft state.

## To Reproduce
1. Go to the "create new work" form, fill out required fields on work details tab, and click "save and continue"
2. Click "Cancel" from the contributors tab. (You will be redirected to the work page, and see that the draft version exists.)
3. Go to your dashboard: you will not see the work because it wasn't indexed.

## Expected behavior
Two possibilities: 
- The draft version should appear on the dashboard (i.e., it should have been indexed)
- OR: The "cancel" could be changed to "delete draft", in which case the draft version should be deleted. (After step 2, above, the user would be directed to their dashboard).

**Comment by awead** [comment]
Index on the first "Save and Continue" event when moving from Work Details to Contributors tab.
