### ISSUE TITLE
Delete unpublished works

### ISSUE THREAD

**Issue by awead** [psu-libraries/scholarsphere#867]
# Feature Request

Many times a user may create a work that doesn't get published, or we create on to "test" things. We should be able to delete this.

## Describe the solution you'd like

If the user has edit access, there's a delete button on the resource page.

## Any alternatives you've considered?

* withdraw the work instead of deleting (Disadvantage: you still have to delete it at some point)
* grant specific `delete` privileges to the only the depositor/admin

## WDLL

* delete any draft version for a work
* if there's only 1 draft, then it deletes the work as well
* single button on the work settings page
* available to anyone with edit access
* admins can delete a version regardless of whether it's been published or not
* may only delete the latest version (applies to admins only)
* if deleting a later version, take the user back to the work settings page upon success; if deleting the only version, take the user back to the dashboard upon success
* must play sound effect of Strong Bad saying [deleted!](https://www.youtube.com/watch?v=hm_yHwnySX8) 👍 "HAHA, that felt great"

**Comment by srerickson** [comment]
As discussed at standup, let's put the "Delete Draft" button on the edit form.

**Comment by srerickson** [comment]
A couple of thoughts @rschenk  :

- The blue bar on the resource page is a little cluttered and confusing, even before the addition of the button. Given that, I'm inclined to say we shouldn't put the button there now, but we may reconsider at some point when we address the larger UI problem.
- I like the button at the bottom of the form but I wonder if we can restrict its functionality to only deleting the draft version? It might be clearer if it says "Delete Draft". This would mean removing the button from the form when admins are using it to change published versions ... gets tricky. 
- I like the idea of having the admin version of the button, used to delete published versions, only in the work settings "danger zone."
- the "danger" tab for the work settings page shouldn't appear if the button wouldn't appear.

**Comment by rschenk** [comment]
@srerickson Can you provide me with some text for the "danger zone" in the admin work and collection settings section?

![Screen Shot 2021-03-18 at 3 13 19 PM](https://user-images.githubusercontent.com/14730/111683986-8a7eb480-87fc-11eb-9e58-f0ac67cceb0c.png)
![Screen Shot 2021-03-18 at 3 13 37 PM](https://user-images.githubusercontent.com/14730/111683998-8d79a500-87fc-11eb-90d5-cf0d774f6a11.png)

**Comment by rschenk** [comment]
@srerickson should you be allowed to delete a work if it has a DOI? If so, what happens to that DOI?

**Comment by srerickson** [comment]
For the danger zone text:

Collection: "Deleting a collection cannot be undone. When a collection is deleted, the works in the collection *are not* deleted. If the collection has a DOI, it will no longer resolve; you are responsible for updating the DOI to a new URI."

Work: "Only the most recent version can be deleted. Deleting a version cannot be undone. If the most recent version is the only version of the work, the work itself will be deleted (regardless of publication status). If the work has a DOI, it will no longer resolve; you are responsible for updating the DOI to a new URI."

As the text implies, admin should be able to delete collections/works even if there is a DOI. If it's not too much trouble, however, it would be good to disable the delete button on collections pages if the collection has a DOI.
