### ISSUE TITLE
Update PublishNewWork service

### ISSUE THREAD

**Issue by awead** [psu-libraries/scholarsphere#898]
In order to integrate with RMD, the `PublishNewWork` service needs to align with the current UI pattern.

## WDLL

* accepts creators without identifiers and does not create Actor records for them
* adds position numbers for creators
* remove default license and work type, require the client to provide them
* remove support for legacy identifiers (this was only for Scholarsphere 3 noids)
* do not create works unless they can be successfully published

**Comment by awead** [comment]
@srerickson Should the API have a default for work type and license, or should the client always _explicitly_ provide them?

**Comment by srerickson** [comment]
The work type and license should be specified in the request, and they should be required.
