### ISSUE TITLE
New field "statement_required"

### ISSUE THREAD

**Issue by srerickson** [psu-libraries/scholarsphere#960]
# Feature Request

Publishers often require the inclusion of a "set statement" when authors upload pre-publication versions of articles to institutional repositories (i.e., for new OA policy). Currently, the only way to include a set statement is to put it in the description, which may cause confusion in the long run. We should create a new field that is part of the work version's meta block.

## Describe the solution you'd like

- a new field called `publisher_statement`

## Any alternatives you've considered?

- just adding the set statement to the description

## What does "done" look like?

- A a field (`publisher_statement`, with label: "Publisher Statement") that is part of the work version's `meta` block. 
- The field input should appear under "optional metadata" in the deposit form
- <s>Change deposit validations so that if a publisher's statement is included, the description is not required.</s>

**Comment by srerickson** [comment]
Field name: `publisher_statement`
Label: "Publisher Statement"
Description: "If the original publisher requires a set statement to upload this work to ScholarSphere, include it here."

**Comment by awead** [comment]
@srerickson How do you want the statement displayed? We could basically just tack it on to the end of the description, or give it another heading similar to the description and display it there.

**Comment by awead** [comment]
@srerickson Also, do we want to allow markdown as we do in the description? I'm thinking no, but just thought I'd ask.

**Comment by awead** [comment]
Something really simple like below, without any additional headings, and just some bold text:

![Screen Shot 2021-05-12 at 5 08 17 PM](https://user-images.githubusercontent.com/312085/118044482-b0c85880-b344-11eb-9aee-2a399a4a2fb8.png)

I think this has the advantage of being more accessible because a screen reader doesn't read any additional headings.

**Comment by srerickson** [comment]
@awead - showing the statement under the description is perfect. I don't even think we we need the bold label ("Publisher's Statement"). It might be useful to have markdown enabled but if it's complicated don't worry about.
