### ISSUE TITLE
Field-specific search problems

### ISSUE THREAD

**Issue by srerickson** [psu-libraries/scholarsphere#965]
# Bug Report
## Description.
On the catalog page, there is a drop-down input for selecting the field to search against ("All Fields", "Title", "Authors",... ). The "All fields" option seems to work as expected but the others don't. For example, selecting "Title" and searching for a work by its title doesn't produce expected results (the work with the title).

## To Reproduce
1. go to catalog page
2. select "title", "author" or field-specific option (not "All Fields").
3. search using title, author, etc. of an existing work

## Expected behavior
- The expected work appears in search results

**Comment by awead** [comment]
## WDLL

* make title search work
* change "Authors" to "Creators"
* make creator search work
* remove subject search

**Comment by awead** [comment]
Add sort by deposit date.
