### ISSUE TITLE
Hitting Enter on a form with action footer activates "Save and Exit" rather than "Save and Continue"

### ISSUE THREAD

**Issue by nicktiberi** [psu-libraries/scholarsphere#997]
# Bug Report

## Description
When editing a work, collection, etc, hitting the Enter key submits the form, but activates the "Save and Exit" option rather than the "Save and Continue" option.

## To Reproduce
1. Edit a draft work.
2. With the "Work Title" field focused, hit the Enter key.
3. The work is saved as draft and the user is taken to the work overview screen.

## Expected behavior
When the Enter key is pressed, the user should progress to the Contributors tab.

**Comment by awead** [comment]
Reorder buttons visually and in the DOM as follows:
![Screen Shot 2021-04-27 at 9 24 14 AM](https://user-images.githubusercontent.com/312085/116249162-85395180-a73a-11eb-8038-34160833bd3c.png)
Swap positions of Cancel and Save and Continue. DOM positioning is indicated by the numbers.
